#!/bin/bash

xlen="$(march-to-cpu-opt --elf-file-path $1 --print-xlen)"
isa="$(march-to-cpu-opt --elf-file-path $1 --print-spike-isa)"
varch="$(march-to-cpu-opt --elf-file-path $1 --print-spike-varch)"

[[ ${isa} != *_zicclsm* ]] && isa="${isa}_zicclsm"

isa_option="--isa=${isa}"

# The Spike version we build in CI does not accept --varch. Passing it makes
# RVV execution tests fail before the test binary even runs.
spike ${isa_option} ${PK_PATH}/pk${xlen} "$@"
