#!/bin/bash

xlen="$(march-to-cpu-opt --elf-file-path $1 --print-xlen)"
isa="$(march-to-cpu-opt --elf-file-path $1 --print-spike-isa)"
varch="$(march-to-cpu-opt --elf-file-path $1 --print-spike-varch)"

[[ -z ${varch} ]] && spike --isa=${isa} ${PK_PATH}/pk${xlen} "$@"
[[ ! -z ${varch} ]] && spike --isa=${isa} --varch=${varch} ${PK_PATH}/pk${xlen} "$@"
