# Copyright (C) 2012-2024 Free Software Foundation, Inc.

# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.

# This file is part of the GDB testsuite.
# It tests the mechanism exposing c++ values to Guile.

load_lib gdb-guile.exp

require allow_cplus_tests allow_guile_tests

standard_testfile .cc

if {[prepare_for_testing "failed to prepare" $testfile $srcfile {debug c++}]} {
    return
}

if ![gdb_guile_runto_main] {
   return
}

gdb_breakpoint [gdb_get_line_number "Break here."]
gdb_continue_to_breakpoint "Break here" ".*Break here.*"

gdb_test "gu (print (value-type (parse-and-eval \"a\")))" \
    "= const A &"
gdb_test "gu (print (value-type (value-referenced-value (parse-and-eval \"a\"))))" \
    "= const A"
gdb_test "gu (print (value-type (parse-and-eval \"int_ref\")))" \
    "= int &"
gdb_test "gu (print (value-type (value-referenced-value (parse-and-eval \"int_ref\"))))" \
    "= int"
gdb_test "gu (print (value-referenced-value (parse-and-eval \"int_ref\")))" \
    "= 10"

gdb_test "gu (print (value-type (value-dereference (parse-and-eval \"int_ptr_ref\"))))" \
    "= int"
gdb_test "gu (print (value-type (value-referenced-value (parse-and-eval \"int_ptr_ref\"))))" \
    "= int_ptr"
gdb_test "gu (print (value-dereference (value-referenced-value (parse-and-eval \"int_ptr_ref\"))))" \
    "= 10"
gdb_test "gu (print (value-referenced-value (value-referenced-value (parse-and-eval \"int_ptr_ref\"))))" \
    "= 10"
