# Copyright 2022-2024 Free Software Foundation, Inc.

# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.

# A simple AMD GPU debugging smoke test.  Run to a breakpoint in device code,
# then continue until the end of the program.

load_lib rocm.exp

standard_testfile .cpp

require allow_hipcc_tests

if {[build_executable "failed to prepare" $testfile $srcfile {debug hip}]} {
    return
}

proc do_test {} {
    clean_restart $::binfile

    with_rocm_gpu_lock {
	if ![runto_main] {
	    return
	}

	gdb_test "with breakpoint pending on -- break do_an_addition" \
	    "Breakpoint $::decimal \\(do_an_addition\\) pending."

	gdb_test "continue" \
	    "Thread $::decimal hit Breakpoint $::decimal, do_an_addition .*"

	gdb_test "continue" \
	    "Inferior 1 .* exited normally.*" \
	    "continue to end"
    }
}

do_test
