# Copyright (C) 2016-2024 Free Software Foundation, Inc.

# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.

# Test expressions involving generics.

load_lib rust-support.exp
require allow_rust_tests
require {can_compile rust}

standard_testfile .rs
if {[prepare_for_testing "failed to prepare" $testfile $srcfile {debug rust}]} {
    return -1
}

set line [gdb_get_line_number "set breakpoint here"]
if {![runto ${srcfile}:$line]} {
    untested "could not run to breakpoint"
    return -1
}

gdb_test "print identity::<u32>(23u32)" " = 23"
gdb_test "ptype identity::<u32>(23u32)" " = u32"
gdb_test "print identity::<f64>(23)" " = 23"
gdb_test "ptype identity::<f64>(23)" " = f64"

gdb_test "print e" " = generics::Hold<i32> \\(7\\)"
gdb_test "print generics::Hold::<i32> (7)" " = generics::Hold<i32> \\(7\\)"
gdb_test "print Hold::<i32> (7)" " = generics::Hold<i32> \\(7\\)"
gdb_test "print identity::< Hold<i32> >(e)" " = generics::Hold<i32> \\(7\\)"
gdb_test "print identity::<generics::Hold<i32> >(e)" \
    " = generics::Hold<i32> \\(7\\)"
gdb_test "print identity::<Hold<i32>>(e)" " = generics::Hold<i32> \\(7\\)"
