# Copyright (C) 2023-2024 Free Software Foundation, Inc.

# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.

# Test expression parsing and evaluation that requires Rust compiler.

load_lib rust-support.exp
require allow_rust_tests
require {can_compile rust}

set v [split [rust_compiler_version] .]
if {[lindex $v 0] == 1 && [lindex $v 1] < 43} {
    untested "128-bit ints require rust 1.43 or greater"
    return -1
}

standard_testfile .rs
if {[prepare_for_testing "failed to prepare" $testfile $srcfile {debug rust}]} {
    return -1
}

set line [gdb_get_line_number "BREAK"]
if {![runto ${srcfile}:$line]} {
    untested "could not run to breakpoint"
    return -1
}

gdb_test "print x" " = 340282366920938463463374607431768211455"
gdb_test "print y" " = 170141183460469231731687303715884105727"

gdb_test "print x / 2" " = 170141183460469231731687303715884105727"
gdb_test "print sm * 2" " = 170141183460469231731687303715884105726"
gdb_test "print sm + sm" " = 170141183460469231731687303715884105726"
gdb_test "print x - y" " = 170141183460469231731687303715884105728"
gdb_test "print -y" " = -170141183460469231731687303715884105727"
gdb_test "print +y" " = 170141183460469231731687303715884105727"

gdb_test "print/x x" " = 0xffffffffffffffffffffffffffffffff"
gdb_test "print x % 4" " = 3"
gdb_test "print !x" " = 0"

gdb_test "print x < 0" " = false"
gdb_test "print -y < 0" " = true"
gdb_test "print x > y" " = true"
gdb_test "print y >= y" " = true"
gdb_test "print y <= y" " = true"
gdb_test "print y == y" " = true"
gdb_test "print x != y" " = true"

gdb_test "print sm << 2" "= 340282366920938463463374607431768211452"
gdb_test "print x >> 2" "= 85070591730234615865843651857942052863"

gdb_test "print/x x & mask" " = 0xf0f0f0f0f0f0f0f0f0f0f0f0f0f0f0f0"
gdb_test "print/x x ^ mask" " = 0xf0f0f0f0f0f0f0f0f0f0f0f0f0f0f0f"
gdb_test "print/x mask | (mask >> 4)" " = 0xffffffffffffffffffffffffffffffff"

gdb_test "print 170141183460469231731687303715884105727" \
    " = 170141183460469231731687303715884105727"
gdb_test "ptype 23i128" "type = i128"
