# Copyright 2023-2024 Free Software Foundation, Inc.

# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.  */

# Exercise tests with the following parameters:
# VL: 64
# SVL: 16, 32, 64, 128
# This set covers 4 (10 ~ 13) out of 25 tests.
#
# These tests are split this way for parallelization and for performance
# reasons.
#
set id_start 10
set id_end 13
source $srcdir/$subdir/aarch64-sme-regs-available.exp.tcl
