# Copyright (C) 2012-2024 Free Software Foundation, Inc.
#
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.

set opts {}
standard_testfile .S .c

if [info exists COMPILE] {
    # make check RUNTESTFLAGS="gdb.arch/amd64-tailcall-ret.exp COMPILE=1"
    standard_testfile .c .c
    lappend opts debug optimize=-O2
} else {
    require is_x86_64_m64_target
}

# Make .c available on the host.
if [is_remote host] {
    gdb_remote_download host $srcdir/$subdir/$srcfile2
}

if { [prepare_for_testing "failed to prepare" ${testfile} ${srcfile} $opts] } {
    return -1
}

if ![runto_main] {
    return -1
}

gdb_breakpoint "g"
gdb_continue_to_breakpoint "first time in g" ".* v = 2;"

gdb_test "return" { f \(\); /\* second \*/} "return" \
         {Make g return now\? \(y or n\) } "y"

gdb_continue_to_breakpoint "second time in g" ".* v = 2;"

gdb_test "finish" " v = 3;"
