# Copyright 2020-2024 Free Software Foundation, Inc.
#
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.

# Check that we can load different RISC-V target descriptions.

require {istarget "riscv*-*-*"}

clean_restart

# Run over every test XML file and check the target description can be
# loaded.
foreach filename [lsort [glob $srcdir/$subdir/riscv-tdesc-loading-*.xml]] {
    if {[is_remote host]} {
       set test_path [remote_download host $filename]
    } else {
       set test_path $filename
    }

    # Currently it is expected that all of the target descriptions in
    # this test will load successfully, so we expect no additonal
    # output from GDB.
    gdb_test_no_output "set tdesc filename $test_path" \
	"check [file tail $filename]"
}
