# Copyright 2014-2024 Free Software Foundation, Inc.

# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.

# This file is part of the gdb testsuite.

# This test exercises set/show disassembler-options results are preserved
# across multiple set architecture calls.

clean_restart

set archs [get_set_option_choices "set architecture" "s390"]
set arch1 "s390:64-bit"
set arch2 "s390:31-bit"
foreach arch [list $arch1 $arch2] {
    if { [lsearch -exact $archs $arch] == -1 } {
	return
    }
}

set option "esa"

with_test_prefix $arch1 {
    gdb_test "set architecture $arch1" \
	"The target architecture is set to \"$arch1\"\." \
	"set architecture $arch1"

    gdb_test_no_output "set disassembler-options"
    gdb_test "show disassembler-options" \
	"The current disassembler options are ''.*" \
	"show NULL disassembler-options"

    gdb_test_no_output "set disassembler-options $option"
    gdb_test "show disassembler-options" \
	"The current disassembler options are '$option'.*" \
	"show disassembler-options $option"
}

# Change architectures and verify the disassembler options have been preserved.

with_test_prefix $arch2 {
    gdb_test "set architecture $arch2" \
	"The target architecture is set to \"$arch2\"\." \
	"set architecture $arch2"

    gdb_test "show disassembler-options" \
	"The current disassembler options are '$option'.*" \
	"show disassembler-options $option"
}
