# Copyright 2014-2024 Free Software Foundation, Inc.
#
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.
#
# This file is part of the gdb testsuite.

# Test single-stepping system call instructions (ta 0x6d) in the two
# cases distinguished by the implementation: sigreturn and all others.
# The sigreturn syscall requires a special analysis since the return
# PC must be extracted from the sigreturn register save area in the
# stack.

require {istarget "sparc*-*-linux*"}

set testfile sparc-sysstep
set srcfile ${testfile}.c
set binfile ${objdir}/${subdir}/${testfile}
set opts {}

if {[prepare_for_testing "failed to prepare" ${binfile} $srcfile {additional_flags=-g}]} {
    return -1
}

if ![runto_main] {
    return -1
}

# Watching the global variable will guarantee that gdb will
# single-step through the whole program.

set lno [gdb_get_line_number "sparc-sysstep.exp: last" $srcfile]

gdb_test "break $srcfile:$lno" "Breakpoint \[0-9\] at .*"
gdb_test_no_output "set can-use-hw-watchpoints 0" ""
gdb_test "watch global" "Watchpoint .*: global"
gdb_test "continue" "Continuing.*${srcfile}:${lno}.*"
