#!/bin/sh
tuple="$1"
shift
args=""
for cf in "$@"; do
    args="$args '$cf',"
done
cat << EOF
[binaries]
c = '${tuple}-gcc'
ar = '${tuple}-ar'
as = '${tuple}-as'
strip = '${tuple}-strip'
nm = '${tuple}-nm'
exe_wrapper = ['sh', '-c', 'test -z "\$PICOLIBC_TEST" || run-riscv "\$@"', 'run-riscv']

[host_machine]
system = 'riscv'
cpu_family = 'riscv'
cpu = 'riscv'
endian = 'little'

[properties]
c_args = [ ${args} '-nostdlib', '-fno-common', '-ftls-model=local-exec' ]
# default multilib is 64 bit, which requires medany
c_args_ = [ '-mcmodel=medany' ]
skip_sanity_check = true
default_flash_addr = '0x80000000'
default_flash_size = '0x00200000'
default_ram_addr   = '0x80200000'
default_ram_size   = '0x00200000'
EOF
