# Copyright 2015-2024 Free Software Foundation, Inc.

# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.

# Anonymous type conversion tests for GDB's C++ compile feature.

load_lib compile-support.exp

standard_testfile .cc

require allow_cplus_tests

require is_c_compiler_gcc

if {[prepare_for_testing $testfile $testfile $srcfile \
	 {debug nowarnings c++}]} {
    return -1
}

if {![runto_main]} {
    return -1
}

gdb_breakpoint [gdb_get_line_number "break here" $srcfile]
gdb_continue_to_breakpoint "testing location"

if {[skip_compile_feature_untested "var = 0"]} {
    return -1
}

# Reminder, "var" is an integer; all these types get converted to `int'.
CompileExpression::new "var"
CompileExpression::test "anon_e" {(3|GHI)}
CompileExpression::test "anon_u.aa" {97( 'a')?}
CompileExpression::test "a.u.b" 0
CompileExpression::test "a.s.len" 5
CompileExpression::test "a.e" {(10|A::AA)}
CompileExpression::test "(*a.s.ptr != 'h')" (0|false)
CompileExpression::test "A::BB" {(11|A::BB)}
CompileExpression::test "ABC" {(1|ABC)}
CompileExpression::test "DEF" {(2|DEF)}
CompileExpression::test "GHI" {(3|GHI)}
CompileExpression::test "JKL" {(4|JKL)}

set k "compile/23588 *-*-*"
CompileExpression::test "anon_s.len" 11 -kfail $k
CompileExpression::test "anon_s.MAGIC" "57005" -kfail $k
CompileExpression::test "anon_s.ua" "48879" -kfail $k
CompileExpression::test "(*anon_s.ptr == 'a')" (1|true) -kfail $k
