# Copyright 2017-2024 Free Software Foundation, Inc.

# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.

# Test whether GDB's C++ compile feature is decaying arrays into pointers.

load_lib compile-support.exp

standard_testfile .cc

require allow_cplus_tests

require is_c_compiler_gcc

if {[prepare_for_testing $testfile $testfile $srcfile \
	 {debug nowarnings c++ additional_flags=-std=c++11}]} {
    return -1
}

if {![runto_main]} {
    return -1
}

if {[skip_compile_feature_untested]} {
    return -1
}

gdb_breakpoint [gdb_get_line_number "break here" $srcfile]
gdb_continue_to_breakpoint "testing location"

gdb_test "compile print integers" " = \\{0, 0, 0, 0, 0, 0, 0, 0, 0, 0\\}"

gdb_test "compile print strings" " = \\{$hex \"hello\", $hex \"hello\",\
    $hex \"hello\", $hex \"hello\", $hex \"hello\", $hex \"hello\",\
    $hex \"hello\", $hex \"hello\", $hex \"hello\", $hex \"hello\"\\}"
