# Copyright 2016-2024 Free Software Foundation, Inc.
#
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.

load_lib "ada.exp"

require allow_ada_tests

standard_ada_testfile main_p324_051

if {[gdb_compile_ada "${srcfile}" "${binfile}" executable [list debug]] != "" } {
  return -1
}

clean_restart ${testfile}

set bp_location [gdb_get_line_number "STOP" ${testdir}/main_p324_051.adb]
runto "main_p324_051.adb:$bp_location"

gdb_test "print assign_arr_input.u2 :=(0.25,0.5,0.75)" \
         " = \\(0\\.25, 0\\.5, 0\\.75\\)"

gdb_test "print assign_arr_input.u2 :=(0.25, others => 0.125)" \
         " = \\(0\\.25, 0\\.125, 0\\.125\\)"

set line [gdb_get_line_number "STOP2" ${testdir}/target_wrapper.adb]
gdb_breakpoint target_wrapper.adb:$line
gdb_continue_to_breakpoint STOP2

gdb_test "print a" " = \\(8, 10, 12\\)"
gdb_test "print a := (2, 4, 6)" " = \\(2, 4, 6\\)" "assign to a"
