# Copyright 2019-2024 Free Software Foundation, Inc.
#
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.

load_lib "ada.exp"

require allow_ada_tests

standard_ada_testfile bias

if {[gdb_compile_ada "${srcfile}" "${binfile}" executable \
	 {debug additional_flags=-fgnat-encodings=minimal}] != "" } {
  return -1
}

clean_restart ${testfile}

set bp_location [gdb_get_line_number "STOP" ${testdir}/bias.adb]
runto "bias.adb:$bp_location"

gdb_test "print x" " = 60"
gdb_test "print y" " = -5"

gdb_test "print cval" " = 65"
gdb_test "print/c cval" " = 65 'A'"

# Some binary arithmetic checks.
gdb_test "print y < y1" " = false"
gdb_test "print y <= y1" " = false"
gdb_test "print y > y1" " = true"
gdb_test "print y >= y1" " = true"
gdb_test "print y = y" " = true"
gdb_test "print y /= y" " = false"
gdb_test "print y /= y1" " = true"

gdb_test "print x + x1" " = 61"
gdb_test "ptype x + x1" "type = range 1 \\.\\. 64"
gdb_test "print x / x1" " = 60"
gdb_test "print x * x1" " = 60"
gdb_test "print x - x1" " = 59"

# Test that storing un-biases.
gdb_test "print x := 5" " = 5"
gdb_test "print x" " = 5" "re-read x after storing"

gdb_test "print spr" " = \\(r => -4, s => -5\\)"
gdb_test "print a" " = \\(-7, -5, -4\\)"
