# Copyright 2023-2024 Free Software Foundation, Inc.
#
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.

# Test calling a function without debug info.

load_lib "ada.exp"

require allow_ada_tests

standard_ada_testfile prog

# Compile pck without debuginfo but prog with it.
if {[gdb_compile_ada $srcdir/$subdir/$testdir/pck.adb \
	 [standard_output_file pck.o] object {}] != ""} {
    return
}

if {[gdb_compile_ada "${srcfile}" "${binfile}" executable \
	 {debug no-force}] != ""} {
    return -1
}

clean_restart ${testfile}

set bp_location [gdb_get_line_number "STOP" ${testdir}/prog.adb]
runto "prog.adb:$bp_location"

# Verify that the function was built without debuginfo.
gdb_test "print plus_one(23)" \
    "plus_one.* has unknown return type; cast the call to its declared return type" \
    "call function without debuginfo"
gdb_test "print integer (plus_one(23))" " = 24" \
    "use cast to call function without debuginfo"
