# Copyright 2018-2024 Free Software Foundation, Inc.
#
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.

load_lib "ada.exp"

require allow_ada_tests

standard_ada_testfile expr_r821_013

if {[gdb_compile_ada "${srcfile}" "${binfile}" executable [list debug ]] != "" } {
  return -1
}

clean_restart ${testfile}

set bp_location [gdb_get_line_number "STOP" ${testdir}/expr_r821_013.adb]
runto "expr_r821_013.adb:$bp_location"

gdb_test "print something()"     " = 124"
gdb_test "print something() + 1" " = 125"
gdb_test "print something() - 2" " = 122"
gdb_test "print something() * 3" " = 372"
gdb_test "print something() / 4" " = 31"

gdb_test "print 1 + something()"   " = 125"
gdb_test "print 246 - something()" " = 122"
gdb_test "print 3 * something()"   " = 372"
gdb_test "print 496 / something()" " = 4"

# Same as above, but without using the parentheses in the call to
# function "Something".

gdb_test "print something"     " = 124"
gdb_test "print something + 1" " = 125"
gdb_test "print something - 2" " = 122"
gdb_test "print something * 3" " = 372"
gdb_test "print something / 4" " = 31"

gdb_test "print 1 + something"   " = 125"
gdb_test "print 246 - something" " = 122"
gdb_test "print 3 * something"   " = 372"
gdb_test "print 496 / something" " = 4"
