# Copyright 2015-2024 Free Software Foundation, Inc.
#
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.

load_lib "ada.exp"

require allow_ada_tests

standard_ada_testfile foo_o525_013

if {[gdb_compile_ada "${srcfile}" "${binfile}" executable [list debug ]] != "" } {
  return -1
}

clean_restart ${testfile}

runto "bar.f"

# Perform a "finish". The output, and in particular the value of
# the return value depends on the target, as sometime the compiler
# will transform it into a struct, which we may or may not be able
# to display, depending on the ABI.  The objective of the test is
# to verify that we don't crash, so keep the expected output simple...
gdb_test "finish" \
         ".*Value returned.*"

# Verify that GDB is still alive...
gdb_test "print 1" \
         "= 1"
