# Copyright 2022-2024 Free Software Foundation, Inc.
#
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.

# Test some literal syntax.

load_lib "ada.exp"

require allow_ada_tests

clean_restart

gdb_test_no_output "set lang ada"
gdb_test "print 7#10#" " = 7"
gdb_test "print 77#10#" "Invalid base: 77."
gdb_test "print 7#8#" "Invalid digit `8' in based literal"

gdb_test "print 8e2" " = 800"
gdb_test "print 9999999999999999999999999999999999999999999999" \
    "Integer literal out of range"
gdb_test "print 2e1000" "Integer literal out of range"

gdb_test "print 16#ffff#" " = 65535"
gdb_test "print 16#f#e1" " = 240"
gdb_test "print 16#1#e10" " = 1099511627776"

gdb_test "print/x 16#7fffffffffffffff#" " = 0x7fffffffffffffff"
gdb_test "print 16#ffffffffffffffff#" " = 18446744073709551615"
