# Copyright 2020-2024 Free Software Foundation, Inc.
#
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.

load_lib "ada.exp"

require allow_ada_tests
require {gnatmake_version_at_least 8}

standard_ada_testfile prot

if {[gdb_compile_ada "${srcfile}" "${binfile}" executable \
	 {debug additional_flags=-gnata}] != ""} {
    return -1
}

load_lib mi-support.exp
set MIFLAGS "-i=mi"

mi_clean_restart $binfile

if {[mi_runto_main] < 0} {
   return 0
}

mi_delete_breakpoints
mi_gdb_reinitialize_dir $srcdir/$subdir
mi_gdb_load ${binfile}

set line [gdb_get_line_number "STOP" ${testdir}/prot.adb]
mi_continue_to_line "$srcfile:$line" "continue to protected method"

# The bug was that this crashed.
mi_gdb_test "-stack-list-arguments --no-frame-filters 1" \
    "\\^done,stack-args=.*"
