# Copyright 2015-2024 Free Software Foundation, Inc.
#
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.

load_lib "ada.exp"

require allow_ada_tests

standard_ada_testfile bar

load_lib mi-support.exp
set MIFLAGS "-i=mi"

foreach_with_prefix scenario {none all minimal} {
    set flags {debug}
    if {$scenario != "none"} {
	lappend flags additional_flags=-fgnat-encodings=$scenario
    }

    if {[gdb_compile_ada "${srcfile}" "${binfile}-${scenario}" executable $flags] != "" } {
	return -1
    }

    mi_clean_restart $binfile-$scenario

    if {[mi_runto_main] < 0} {
	return 0
    }

    set bp_location [gdb_get_line_number "STOP" ${testdir}/bar.adb]
    mi_continue_to_line \
	"bar.adb:$bp_location" \
	"stop at start of main Ada procedure"

    mi_gdb_test "-var-create vta * vta" \
	"\\^done,name=\"vta\",numchild=\"0\",.*" \
	"create bt varobj"
}
