# Copyright 2017-2024 Free Software Foundation, Inc.
#
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.

load_lib "ada.exp"

require allow_ada_tests

standard_ada_testfile foo_qb07_057

if {[gdb_compile_ada "${srcfile}" "${binfile}" executable ""] != "" } {
  return -1
}

clean_restart ${testfile}

if {![runto "_ada_foo_qb07_057"]} {
  return
}

gdb_test_no_output "set language ada"

gdb_test "print some_minsym" \
         "'some_minsym' has unknown type; cast it to its declared type"

gdb_test "print integer(some_minsym)" \
         " = 1234"

gdb_test "print &some_minsym" \
         " = \\(access <data variable, no debug info>\\) $hex <some_minsym>"

gdb_test "print /x integer(&some_minsym)" \
         " = $hex"
