# Copyright 2013-2024 Free Software Foundation, Inc.
#
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.

load_lib "ada.exp"
load_lib gdb-python.exp

require allow_ada_tests allow_python_tests

standard_ada_testfile foo

if {[gdb_compile_ada "${srcfile}" "${binfile}" executable [list debug]] != "" } {
  return -1
}

clean_restart ${testfile}

set bp_location [gdb_get_line_number "STOP" ${testdir}/foo.adb]
runto "foo.adb:$bp_location"

gdb_test "python print(int(gdb.parse_and_eval('sr')))" \
         "48"

gdb_test "python print(int(gdb.parse_and_eval('si')))" \
         "740804"

gdb_test "python print(int(gdb.parse_and_eval('ir')))" \
         "974"

gdb_test "python print(gdb.parse_and_eval('si').type)" \
    "foo\\.small_integer" "print type"
gdb_test "python print(gdb.parse_and_eval('si').type.name)" \
    "foo\\.small_integer" "print type name"

gdb_test "python print(gdb.selected_inferior().main_name)" \
    "_ada_foo" \
    "print main name"
