# Copyright 2015-2024 Free Software Foundation, Inc.
#
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.

load_lib "ada.exp"

require allow_ada_tests

standard_ada_testfile var_arr_typedef

if {[gdb_compile_ada "${srcfile}" "${binfile}" executable [list debug]] != "" } {
  return -1
}

clean_restart ${testfile}

set bp_location [gdb_get_line_number "BREAK" ${testdir}/var_arr_typedef.adb]
runto "var_arr_typedef.adb:$bp_location"

set ra "\\(i => 3, b => false\\)"
set rb "\\(i => 2, b => true\\)"

set va "\\($ra, $ra, $rb, $rb\\)"
set vb "\\($rb, $rb, $ra, $ra\\)"

set a "\\($va, $va, $vb, $vb\\)"

gdb_test "print va" \
         " = $va"

gdb_test "print vb" \
         " = $vb"

gdb_test "print a" \
         " = $a"
