# Copyright 2023-2024 Free Software Foundation, Inc.
#
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.

load_lib "ada.exp"

require allow_ada_tests
require {gnatmake_version_at_least 11}

standard_ada_testfile prog

if {[gdb_compile_ada "${srcfile}" "${binfile}" executable {debug}] != ""} {
    return -1
}

clean_restart ${testfile}

set bp_location [gdb_get_line_number "START" ${testdir}/prog.adb]
runto "prog.adb:$bp_location"

gdb_test "print x" " = 170141183460469231731687303715884105727"
gdb_test "print x / 2" " = 85070591730234615865843651857942052863"
gdb_test "print (x / 4) * 2" " = 85070591730234615865843651857942052862"
gdb_test "print x - x" " = 0"
gdb_test "print x - 99 + 1" " = 170141183460469231731687303715884105629"
gdb_test "print -x" " = -170141183460469231731687303715884105727"
gdb_test "print +x" " = 170141183460469231731687303715884105727"

gdb_test "print 170141183460469231731687303715884105727" \
    " = 170141183460469231731687303715884105727"
gdb_test "print x = 170141183460469231731687303715884105727" \
    " = true"
