# Copyright 2018-2024 Free Software Foundation, Inc.
#
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.

load_lib "ada.exp"

require allow_ada_tests

standard_ada_testfile foo_ra10_006

if {[gdb_compile_ada "${srcfile}" "${binfile}" executable {debug}] != ""} {
    return -1
}

clean_restart ${testfile}

set bp_location [gdb_get_line_number "START" ${testdir}/foo_ra10_006.adb]
runto "foo_ra10_006.adb:$bp_location"

# Insert a watchpoint on argument X

gdb_test "watch -location pck.global_var" \
         ".*atchpoint \[0-9\]+: -location pck.global_var"

# Continue again.  We should be stopped at the (internal) breakpoint
# that we setup to delete the watchpoint as soon as the program leaves
# the watchpoint scope.

gdb_test "continue" \
    "Continuing.*\[Ww\]atchpoint .*: .*New value = 1.*" \
    "continue with watch -location"
