/* This file is automatically generated by i386-gen.  Do not edit!  */
/* Copyright (C) 2007-2024 Free Software Foundation, Inc.

   This file is part of the GNU opcodes library.

   This library is free software; you can redistribute it and/or modify
   it under the terms of the GNU General Public License as published by
   the Free Software Foundation; either version 3, or (at your option)
   any later version.

   It is distributed in the hope that it will be useful, but WITHOUT
   ANY WARRANTY; without even the implied warranty of MERCHANTABILITY
   or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU General Public
   License for more details.

   You should have received a copy of the GNU General Public License
   along with this program; if not, write to the Free Software
   Foundation, Inc., 51 Franklin Street - Fifth Floor, Boston,
   MA 02110-1301, USA.  */

extern const char i386_mnemonics[];

#define MN_ud0 0x1
#define MN_prefetcht0 0x5
#define MN_prefetchit0 0x10
#define MN_xsha1 0x1c
#define MN_fld1 0x22
#define MN_ud1 0x27
#define MN_sha1msg1 0x2b
#define MN_vsha512msg1 0x34
#define MN_vsm3msg1 0x40
#define MN_sha256msg1 0x49
#define MN_fprem1 0x54
#define MN_f2xm1 0x5b
#define MN_fyl2xp1 0x61
#define MN_tileloaddt1 0x69
#define MN_prefetcht1 0x75
#define MN_prefetchit1 0x80
#define MN_pfrcpit1 0x8c
#define MN_pfrsqit1 0x95
#define MN_int1 0x9e
#define MN_prefetchwt1 0xa3
#define MN_vmovdqa32 0xaf
#define MN_data32 0xb9
#define MN_crc32 0xc0
#define MN_endbr32 0xc6
#define MN_addr32 0xce
#define MN_vmovdqu32 0xd5
#define MN_ud2 0xdf
#define MN_fldlg2 0xe3
#define MN_sha1msg2 0xea
#define MN_vsha512msg2 0xf3
#define MN_vsm3msg2 0xff
#define MN_sha256msg2 0x108
#define MN_push2 0x113
#define MN_fldln2 0x119
#define MN_pop2 0x120
#define MN_vsha512rnds2 0x125
#define MN_vsm3rnds2 0x132
#define MN_sha256rnds2 0x13c
#define MN_prefetcht2 0x148
#define MN_pfrcpit2 0x153
#define MN_vbroadcastf32x2 0x15c
#define MN_vbroadcasti32x2 0x16c
#define MN_vshuff64x2 0x17c
#define MN_vextractf64x2 0x187
#define MN_vinsertf64x2 0x195
#define MN_vbroadcastf64x2 0x1a2
#define MN_vshufi64x2 0x1b2
#define MN_vextracti64x2 0x1bd
#define MN_vinserti64x2 0x1cb
#define MN_vbroadcasti64x2 0x1d8
#define MN_int3 0x1e8
#define MN_vmovdqa64 0x1ed
#define MN_xsavec64 0x1f7
#define MN_xsave64 (MN_fxsave64 + 1)
#define MN_fxsave64 0x200
#define MN_endbr64 0x209
#define MN_xrstor64 (MN_fxrstor64 + 1)
#define MN_fxrstor64 0x211
#define MN_xsaves64 0x21b
#define MN_xrstors64 0x224
#define MN_xsaveopt64 0x22e
#define MN_vmovdqu64 0x239
#define MN_rex64 0x243
#define MN_sha1rnds4 0x249
#define MN_vsm4rnds4 0x253
#define MN_vshuff32x4 0x25d
#define MN_vextractf32x4 0x268
#define MN_vinsertf32x4 0x276
#define MN_vbroadcastf32x4 0x283
#define MN_vshufi32x4 0x293
#define MN_vextracti32x4 0x29e
#define MN_vinserti32x4 0x2ac
#define MN_vbroadcasti32x4 0x2b9
#define MN_vextractf64x4 0x2c9
#define MN_vinsertf64x4 0x2d7
#define MN_vbroadcastf64x4 0x2e4
#define MN_vextracti64x4 0x2f4
#define MN_vinserti64x4 0x302
#define MN_vbroadcasti64x4 0x30f
#define MN_vsm4key4 0x31f
#define MN_data16 0x328
#define MN_vcvtne2ps2bf16 0x32f
#define MN_vcvtneps2bf16 0x33e
#define MN_addr16 0x34c
#define MN_vmovdqu16 0x353
#define MN_xsha256 0x35d
#define MN_encodekey256 0x365
#define MN_vperm2f128 0x372
#define MN_vextractf128 0x37d
#define MN_vinsertf128 0x38a
#define MN_vbroadcastf128 0x396
#define MN_vperm2i128 0x3a5
#define MN_vextracti128 0x3b0
#define MN_vinserti128 0x3bd
#define MN_vbroadcasti128 0x3c9
#define MN_encodekey128 0x3d8
#define MN_vmovdqu8 0x3e5
#define MN_vextractf32x8 0x3ee
#define MN_vinsertf32x8 0x3fc
#define MN_vbroadcastf32x8 0x409
#define MN_vextracti32x8 0x419
#define MN_vinserti32x8 0x427
#define MN_vbroadcasti32x8 0x434
#define MN_ud2a 0x444
#define MN_aaa 0x449
#define MN_daa 0x44d
#define MN_ssca 0x451
#define MN_lea 0x456
#define MN_invlpga 0x45a
#define MN_pusha 0x462
#define MN_ja 0x468
#define MN_jna 0x46b
#define MN_setna 0x46f
#define MN_cmovna (MN_fcmovna + 1)
#define MN_fcmovna 0x475
#define MN_popa 0x47d
#define MN_movntdqa (MN_vmovntdqa + 1)
#define MN_vmovntdqa 0x482
#define MN_movdqa (MN_vmovdqa + 1)
#define MN_vmovdqa 0x48c
#define MN_seta 0x494
#define MN_prefetchnta 0x499
#define MN_cmova (MN_fcmova + 1)
#define MN_fcmova 0x4a5
#define MN_rex_b 0x4ac
#define MN_ud2b 0x4b2
#define MN_vpermi2b 0x4b7
#define MN_vpmovm2b 0x4c0
#define MN_vpermt2b 0x4c9
#define MN_movdir64b 0x4d2
#define MN_cmpxchg16b 0x4dc
#define MN_cmpxchg8b 0x4e7
#define MN_vpshab 0x4f1
#define MN_sbb 0x4f8
#define MN_psubb (MN_vpsubb + 1)
#define MN_vpsubb 0x4fc
#define MN_xcrypt_ecb 0x503
#define MN_xcryptecb 0x50e
#define MN_llwpcb 0x518
#define MN_slwpcb 0x51f
#define MN_kaddb 0x526
#define MN_paddb (MN_vpaddb + 1)
#define MN_vpaddb 0x52c
#define MN_kandb 0x533
#define MN_vpexpandb 0x539
#define MN_vpmovusdb 0x543
#define MN_vpmovsdb 0x54d
#define MN_vpmovdb 0x556
#define MN_vpcomgeb 0x55e
#define MN_vpcomleb 0x567
#define MN_vpcmpnleb 0x570
#define MN_vpcmpleb 0x57a
#define MN_vpcomfalseb 0x583
#define MN_vpcomtrueb 0x58f
#define MN_xcrypt_cfb 0x59a
#define MN_xcryptcfb 0x5a5
#define MN_xcrypt_ofb 0x5af
#define MN_xcryptofb 0x5ba
#define MN_pshufb (MN_vpshufb + 1)
#define MN_vpshufb 0x5c4
#define MN_invlpgb 0x5cc
#define MN_pavgb (MN_vpavgb + 1)
#define MN_vpavgb 0x5d4
#define MN_jb 0x5db
#define MN_pbndkb 0x5de
#define MN_pmovmskb (MN_vpmovmskb + 1)
#define MN_vpmovmskb 0x5e5
#define MN_vpshlb 0x5ef
#define MN_kshiftlb 0x5f6
#define MN_gf2p8mulb (MN_vgf2p8mulb + 1)
#define MN_vgf2p8mulb 0x5ff
#define MN_vpblendmb 0x60a
#define MN_vptestnmb 0x614
#define MN_vpcomb 0x61e
#define MN_vpshufbitqmb 0x625
#define MN_vpermb 0x632
#define MN_vptestmb 0x639
#define MN_kandnb 0x642
#define MN_psignb (MN_vpsignb + 1)
#define MN_vpsignb 0x649
#define MN_jnb 0x651
#define MN_setnb 0x655
#define MN_cmovnb (MN_fcmovnb + 1)
#define MN_fcmovnb 0x65b
#define MN_vpcmpb 0x663
#define MN_vpcomeqb 0x66a
#define MN_gf2p8affineqb (MN_vgf2p8affineqb + 1)
#define MN_vgf2p8affineqb 0x673
#define MN_vpcomneqb 0x682
#define MN_vpcmpneqb 0x68c
#define MN_pcmpeqb (MN_vpcmpeqb + 1)
#define MN_vpcmpeqb 0x696
#define MN_vpmovusqb 0x69f
#define MN_vpmovsqb 0x6a9
#define MN_vpmultishiftqb 0x6b2
#define MN_gf2p8affineinvqb (MN_vgf2p8affineinvqb + 1)
#define MN_vgf2p8affineinvqb 0x6c1
#define MN_vpmovqb 0x6d3
#define MN_rex_rb 0x6db
#define MN_korb 0x6e2
#define MN_kxnorb 0x6e7
#define MN_kxorb 0x6ee
#define MN_pinsrb (MN_vpinsrb + 1)
#define MN_vpinsrb 0x6f4
#define MN_kshiftrb 0x6fc
#define MN_pextrb (MN_vpextrb + 1)
#define MN_vpextrb 0x705
#define MN_rex_wrb 0x70d
#define MN_pabsb (MN_vpabsb + 1)
#define MN_vpabsb 0x715
#define MN_psubsb (MN_vpsubsb + 1)
#define MN_vpsubsb 0x71c
#define MN_paddsb (MN_vpaddsb + 1)
#define MN_vpaddsb 0x724
#define MN_pminsb (MN_vpminsb + 1)
#define MN_vpminsb 0x72c
#define MN_vpcompressb 0x734
#define MN_psubusb (MN_vpsubusb + 1)
#define MN_vpsubusb 0x740
#define MN_paddusb (MN_vpaddusb + 1)
#define MN_vpaddusb 0x749
#define MN_pavgusb 0x752
#define MN_movsb 0x75a
#define MN_pmaxsb (MN_vpmaxsb + 1)
#define MN_vpmaxsb 0x760
#define MN_setb 0x768
#define MN_vpcomgtb 0x76d
#define MN_pcmpgtb (MN_vpcmpgtb + 1)
#define MN_vpcmpgtb 0x776
#define MN_vpcomltb 0x77f
#define MN_vpcmpnltb 0x788
#define MN_vpcmpltb 0x792
#define MN_vpopcntb 0x79b
#define MN_knotb 0x7a4
#define MN_vprotb 0x7aa
#define MN_vpbroadcastb 0x7b1
#define MN_ktestb 0x7be
#define MN_kortestb 0x7c5
#define MN_vpcomgeub 0x7ce
#define MN_vpcomleub 0x7d8
#define MN_vpcmpnleub 0x7e2
#define MN_vpcmpleub 0x7ed
#define MN_vpcomfalseub 0x7f7
#define MN_vpcomtrueub 0x804
#define MN_vpcomub 0x810
#define MN_pminub (MN_vpminub + 1)
#define MN_vpminub 0x818
#define MN_vpcmpub 0x820
#define MN_vpcomequb 0x828
#define MN_vpcomnequb 0x832
#define MN_vpcmpnequb 0x83d
#define MN_vpcmpequb 0x848
#define MN_sub (MN_fsub + 1)
#define MN_fsub (MN_pfsub + 1)
#define MN_pfsub 0x852
#define MN_fisub 0x858
#define MN_vpcomgtub 0x85e
#define MN_vpcomltub 0x868
#define MN_vpcmpnltub 0x872
#define MN_vpcmpltub 0x87d
#define MN_pmaxub (MN_vpmaxub + 1)
#define MN_vpmaxub 0x887
#define MN_pblendvb (MN_vpblendvb + 1)
#define MN_vpblendvb 0x88f
#define MN_cmovb (MN_fcmovb + 1)
#define MN_fcmovb 0x899
#define MN_kmovb 0x8a0
#define MN_rex_wb 0x8a6
#define MN_clwb 0x8ad
#define MN_packsswb (MN_vpacksswb + 1)
#define MN_vpacksswb 0x8b2
#define MN_packuswb (MN_vpackuswb + 1)
#define MN_vpackuswb 0x8bc
#define MN_vpmovuswb 0x8c6
#define MN_vpmovswb 0x8d0
#define MN_vpmovwb 0x8d9
#define MN_rex_xb 0x8e1
#define MN_rex_rxb 0x8e8
#define MN_rex_wrxb 0x8f0
#define MN_rex_wxb 0x8f9
#define MN_movzb 0x901
#define MN_clac 0x907
#define MN_stac 0x90c
#define MN_xcrypt_cbc 0x911
#define MN_xcryptcbc 0x91c
#define MN_pfacc 0x926
#define MN_pfnacc 0x92c
#define MN_pfpnacc 0x933
#define MN_adc 0x93b
#define MN_dec (MN_aesdec + 3)
#define MN_aesdec (MN_vaesdec + 1)
#define MN_vaesdec 0x93f
#define MN_getsec 0x947
#define MN_xsavec 0x94e
#define MN_blcic 0x955
#define MN_blsic 0x95b
#define MN_jc 0x961
#define MN_t1mskc 0x964
#define MN_clc 0x96b
#define MN_cmc 0x96f
#define MN_aesimc (MN_vaesimc + 1)
#define MN_vaesimc 0x973
#define MN_rdpmc 0x97b
#define MN_aesenc (MN_vaesenc + 1)
#define MN_vaesenc 0x981
#define MN_inc 0x989
#define MN_jnc 0x98d
#define MN_setnc 0x991
#define MN_vmfunc 0x997
#define MN_cmovnc 0x99e
#define MN_tlbsync 0x9a5
#define MN_rdtsc 0x9ad
#define MN_btc 0x9b3
#define MN_setc 0x9b7
#define MN_stc 0x9bc
#define MN_cmovc 0x9c0
#define MN_vpermi2d 0x9c6
#define MN_vpmovm2d 0x9cf
#define MN_vpermt2d 0x9d8
#define MN_vpbroadcastmw2d 0x9e1
#define MN_aad 0x9f1
#define MN_vmread 0x9f5
#define MN_vpshad 0x9fc
#define MN_vmload 0xa03
#define MN_psrad (MN_vpsrad + 1)
#define MN_vpsrad 0xa0a
#define MN_vphaddbd 0xa11
#define MN_vphaddubd 0xa1a
#define MN_phsubd (MN_vphsubd + 1)
#define MN_vphsubd 0xa24
#define MN_psubd (MN_vpsubd + 1)
#define MN_vpsubd 0xa2c
#define MN_pmovsxbd (MN_vpmovsxbd + 1)
#define MN_vpmovsxbd 0xa33
#define MN_pmovzxbd (MN_vpmovzxbd + 1)
#define MN_vpmovzxbd 0xa3d
#define MN_add (MN_aadd + 1)
#define MN_aadd 0xa47
#define MN_fadd (MN_pfadd + 1)
#define MN_pfadd 0xa4c
#define MN_fiadd 0xa52
#define MN_tileloadd 0xa58
#define MN_xadd (MN_cmpnaxadd + 5)
#define MN_cmpnaxadd 0xa62
#define MN_cmpaxadd 0xa6c
#define MN_cmpnbxadd 0xa75
#define MN_cmpbxadd 0xa7f
#define MN_cmpncxadd 0xa88
#define MN_cmpcxadd 0xa92
#define MN_cmpnaexadd 0xa9b
#define MN_cmpaexadd 0xaa6
#define MN_cmpnbexadd 0xab0
#define MN_cmpbexadd 0xabb
#define MN_cmpngexadd 0xac5
#define MN_cmpgexadd 0xad0
#define MN_cmpnlexadd 0xada
#define MN_cmplexadd 0xae5
#define MN_cmpnexadd 0xaef
#define MN_cmpexadd 0xaf9
#define MN_cmppexadd 0xb02
#define MN_cmpngxadd 0xb0c
#define MN_cmpgxadd 0xb16
#define MN_cmpnlxadd 0xb1f
#define MN_cmplxadd 0xb29
#define MN_cmpnoxadd 0xb32
#define MN_cmpoxadd 0xb3c
#define MN_cmppoxadd 0xb45
#define MN_cmpnpxadd 0xb4f
#define MN_cmppxadd 0xb59
#define MN_cmpnsxadd 0xb62
#define MN_cmpsxadd 0xb6c
#define MN_cmpnzxadd 0xb75
#define MN_cmpzxadd 0xb7f
#define MN_phaddd (MN_vphaddd + 1)
#define MN_vphaddd 0xb88
#define MN_kaddd 0xb90
#define MN_paddd (MN_vpaddd + 1)
#define MN_vpaddd 0xb96
#define MN_vpshldd 0xb9d
#define MN_kandd 0xba5
#define MN_vpandd 0xbab
#define MN_vpexpandd 0xbb2
#define MN_vpblendd 0xbbc
#define MN_vpgatherdd 0xbc5
#define MN_vpscatterdd 0xbd0
#define MN_vpshrdd 0xbdc
#define MN_vpmacsdd 0xbe4
#define MN_vpmacssdd 0xbed
#define MN_rdseed 0xbf7
#define MN_vpcomged 0xbfe
#define MN_vpcomled 0xc07
#define MN_vpcmpnled 0xc10
#define MN_vpcmpled 0xc1a
#define MN_tilestored 0xc23
#define MN_vpcomfalsed 0xc2e
#define MN_vpcomtrued 0xc3a
#define MN_pi2fd 0xc45
#define MN_pshufd (MN_vpshufd + 1)
#define MN_vpshufd 0xc4b
#define MN_vpternlogd 0xc53
#define MN_pf2id 0xc5e
#define MN_invpcid 0xc64
#define MN_rdpid 0xc6c
#define MN_invvpid 0xc72
#define MN_cpuid 0xc7a
#define MN_fbld 0xc80
#define MN_cld 0xc85
#define MN_fld 0xc89
#define MN_shld (MN_vpshld + 2)
#define MN_vpshld 0xc8d
#define MN_fild 0xc94
#define MN_pslld (MN_vpslld + 1)
#define MN_vpslld 0xc99
#define MN_pmulld (MN_vpmulld + 1)
#define MN_vpmulld 0xca0
#define MN_vprold 0xca8
#define MN_psrld (MN_vpsrld + 1)
#define MN_vpsrld 0xcaf
#define MN_vmptrld 0xcb6
#define MN_kshiftld 0xcbe
#define MN_enqcmd 0xcc7
#define MN_vpblendmd 0xcce
#define MN_vptestnmd 0xcd8
#define MN_vpcomd 0xce2
#define MN_vpermd 0xce9
#define MN_vptestmd 0xcf0
#define MN_and (MN_aand + 1)
#define MN_aand 0xcf9
#define MN_pand (MN_vpand + 1)
#define MN_vpand 0xcfe
#define MN_rdrand 0xd04
#define MN_bnd 0xd0b
#define MN_kandnd 0xd0f
#define MN_vpandnd 0xd16
#define MN_xend 0xd1e
#define MN_valignd 0xd23
#define MN_psignd (MN_vpsignd + 1)
#define MN_vpsignd 0xd2b
#define MN_bound 0xd33
#define MN_slod 0xd39
#define MN_vfmaddsub231pd 0xd3e
#define MN_vfmsub231pd 0xd4d
#define MN_vfnmsub231pd 0xd59
#define MN_vfmsubadd231pd 0xd66
#define MN_vfmadd231pd 0xd75
#define MN_vfnmadd231pd 0xd81
#define MN_vfmaddsub132pd 0xd8e
#define MN_vfmsub132pd 0xd9d
#define MN_vfnmsub132pd 0xda9
#define MN_vfmsubadd132pd 0xdb6
#define MN_vfmadd132pd 0xdc5
#define MN_vfnmadd132pd 0xdd1
#define MN_vcvtph2pd 0xdde
#define MN_vpermi2pd 0xde8
#define MN_cvtpi2pd 0xdf2
#define MN_vpermil2pd 0xdfb
#define MN_vexp2pd 0xe06
#define MN_cvtdq2pd (MN_vcvtdq2pd + 1)
#define MN_vcvtdq2pd 0xe0e
#define MN_vcvtudq2pd 0xe18
#define MN_vcvtqq2pd 0xe23
#define MN_vcvtuqq2pd 0xe2d
#define MN_cvtps2pd (MN_vcvtps2pd + 1)
#define MN_vcvtps2pd 0xe38
#define MN_vpermt2pd 0xe42
#define MN_vfmaddsub213pd 0xe4c
#define MN_vfmsub213pd 0xe5b
#define MN_vfnmsub213pd 0xe67
#define MN_vfmsubadd213pd 0xe74
#define MN_vfmadd213pd 0xe83
#define MN_vfnmadd213pd 0xe8f
#define MN_vrcp14pd 0xe9c
#define MN_vrsqrt14pd 0xea5
#define MN_vrcp28pd 0xeb0
#define MN_vrsqrt28pd 0xeb9
#define MN_movapd (MN_vmovapd + 1)
#define MN_vmovapd 0xec4
#define MN_pswapd 0xecc
#define MN_subpd (MN_addsubpd + 3)
#define MN_addsubpd (MN_vfmaddsubpd + 3)
#define MN_vfmaddsubpd 0xed3
#define MN_vaddsubpd 0xedf
#define MN_hsubpd (MN_vhsubpd + 1)
#define MN_vhsubpd 0xee9
#define MN_vfmsubpd 0xef1
#define MN_vfnmsubpd 0xefa
#define MN_vsubpd 0xf04
#define MN_vgatherpf0dpd 0xf0b
#define MN_vscatterpf0dpd 0xf19
#define MN_vgatherpf1dpd 0xf28
#define MN_vscatterpf1dpd 0xf36
#define MN_addpd (MN_vfmsubaddpd + 6)
#define MN_vfmsubaddpd 0xf45
#define MN_haddpd (MN_vhaddpd + 1)
#define MN_vhaddpd 0xf51
#define MN_vfmaddpd 0xf59
#define MN_vfnmaddpd 0xf62
#define MN_vaddpd 0xf6c
#define MN_andpd (MN_vexpandpd + 4)
#define MN_vexpandpd 0xf73
#define MN_vandpd 0xf7d
#define MN_blendpd (MN_vblendpd + 1)
#define MN_vblendpd 0xf84
#define MN_roundpd (MN_vroundpd + 1)
#define MN_vroundpd 0xf8d
#define MN_vgatherdpd 0xf96
#define MN_vscatterdpd 0xfa1
#define MN_cmpunordpd (MN_vcmpunordpd + 1)
#define MN_vcmpunordpd 0xfad
#define MN_cmpordpd (MN_vcmpordpd + 1)
#define MN_vcmpordpd 0xfb9
#define MN_vreducepd 0xfc3
#define MN_vrangepd 0xfcd
#define MN_vcmpngepd 0xfd6
#define MN_vcmpgepd 0xfe0
#define MN_vrndscalepd 0xfe9
#define MN_cmpnlepd (MN_vcmpnlepd + 1)
#define MN_vcmpnlepd 0xff5
#define MN_cmplepd (MN_vcmplepd + 1)
#define MN_vcmplepd 0xfff
#define MN_vcmpfalsepd 0x1008
#define MN_vcmptruepd 0x1014
#define MN_vscalefpd 0x101f
#define MN_shufpd (MN_vshufpd + 1)
#define MN_vshufpd 0x1029
#define MN_unpckhpd (MN_vunpckhpd + 1)
#define MN_vunpckhpd 0x1031
#define MN_movhpd (MN_vmovhpd + 1)
#define MN_vmovhpd 0x103b
#define MN_movmskpd (MN_vmovmskpd + 1)
#define MN_vmovmskpd 0x1043
#define MN_vpermilpd 0x104d
#define MN_unpcklpd (MN_vunpcklpd + 1)
#define MN_vunpcklpd 0x1057
#define MN_mulpd (MN_vmulpd + 1)
#define MN_vmulpd 0x1061
#define MN_movlpd (MN_vmovlpd + 1)
#define MN_vmovlpd 0x1068
#define MN_vpcmpd 0x1070
#define MN_vblendmpd 0x1077
#define MN_vfixupimmpd 0x1081
#define MN_vpermpd 0x108d
#define MN_andnpd (MN_vandnpd + 1)
#define MN_vandnpd 0x1095
#define MN_minpd (MN_vminpd + 1)
#define MN_vminpd 0x109d
#define MN_dppd (MN_vdppd + 1)
#define MN_vdppd 0x10a4
#define MN_cmppd (MN_vcmppd + 1)
#define MN_vcmppd 0x10aa
#define MN_vgetexppd 0x10b1
#define MN_vgatherpf0qpd 0x10bb
#define MN_vscatterpf0qpd 0x10c9
#define MN_vgatherpf1qpd 0x10d8
#define MN_vscatterpf1qpd 0x10e6
#define MN_vcmpunord_qpd 0x10f5
#define MN_vcmpord_qpd 0x1103
#define MN_cmpneqpd (MN_vcmpneqpd + 1)
#define MN_vcmpneqpd 0x110f
#define MN_cmpeqpd (MN_vcmpeqpd + 1)
#define MN_vcmpeqpd 0x1119
#define MN_vcmpge_oqpd 0x1122
#define MN_vcmple_oqpd 0x112e
#define MN_vcmpfalse_oqpd 0x113a
#define MN_vcmpneq_oqpd 0x1149
#define MN_vcmpeq_oqpd 0x1156
#define MN_vcmpgt_oqpd 0x1162
#define MN_vcmplt_oqpd 0x116e
#define MN_vgatherqpd 0x117a
#define MN_vscatterqpd 0x1185
#define MN_vcmpnge_uqpd 0x1191
#define MN_vcmpnle_uqpd 0x119e
#define MN_vcmptrue_uqpd 0x11ab
#define MN_vcmpneq_uqpd 0x11b9
#define MN_vcmpeq_uqpd 0x11c6
#define MN_vcmpngt_uqpd 0x11d2
#define MN_vcmpnlt_uqpd 0x11df
#define MN_orpd (MN_vorpd + 1)
#define MN_vorpd 0x11ec
#define MN_xorpd (MN_vxorpd + 1)
#define MN_vxorpd 0x11f2
#define MN_vcmpunord_spd 0x11f9
#define MN_vcmpord_spd 0x1207
#define MN_vcmpge_ospd 0x1213
#define MN_vcmple_ospd 0x121f
#define MN_vcmpfalse_ospd 0x122b
#define MN_vcmpneq_ospd 0x123a
#define MN_vcmpeq_ospd 0x1247
#define MN_vcmpgt_ospd 0x1253
#define MN_vcmplt_ospd 0x125f
#define MN_vfpclasspd 0x126b
#define MN_incsspd 0x1276
#define MN_rdsspd 0x127e
#define MN_vcompresspd 0x1285
#define MN_vcmpnge_uspd 0x1291
#define MN_vcmpnle_uspd 0x129e
#define MN_vcmptrue_uspd 0x12ab
#define MN_vcmpneq_uspd 0x12b9
#define MN_vcmpeq_uspd 0x12c6
#define MN_vcmpngt_uspd 0x12d2
#define MN_vcmpnlt_uspd 0x12df
#define MN_vcmpngtpd 0x12ec
#define MN_vcmpgtpd 0x12f6
#define MN_cmpnltpd (MN_vcmpnltpd + 1)
#define MN_vcmpnltpd 0x12ff
#define MN_cmpltpd (MN_vcmpltpd + 1)
#define MN_vcmpltpd 0x1309
#define MN_vgetmantpd 0x1312
#define MN_movntpd (MN_vmovntpd + 1)
#define MN_vmovntpd 0x131d
#define MN_sqrtpd (MN_vsqrtpd + 1)
#define MN_vsqrtpd 0x1326
#define MN_vtestpd 0x132e
#define MN_movupd (MN_vmovupd + 1)
#define MN_vmovupd 0x1336
#define MN_blendvpd (MN_vblendvpd + 1)
#define MN_vblendvpd 0x133e
#define MN_divpd (MN_vdivpd + 1)
#define MN_vdivpd 0x1348
#define MN_vmaskmovpd 0x134f
#define MN_maxpd (MN_vmaxpd + 1)
#define MN_vmaxpd 0x135a
#define MN_vfrczpd 0x1361
#define MN_vpcomeqd 0x1369
#define MN_vpcomneqd 0x1372
#define MN_vpcmpneqd 0x137c
#define MN_pcmpeqd (MN_vpcmpeqd + 1)
#define MN_vpcmpeqd 0x1386
#define MN_vpgatherqd 0x138f
#define MN_vpscatterqd 0x139a
#define MN_vpmovusqd 0x13a6
#define MN_vpmovsqd 0x13b0
#define MN_vpmovqd 0x13b9
#define MN_shrd 0x13c1
#define MN_kord 0x13c6
#define MN_kxnord 0x13cb
#define MN_vpord 0x13d2
#define MN_vprord 0x13d8
#define MN_word (MN_aword + 1)
#define MN_aword 0x13df
#define MN_dword (MN_adword + 1)
#define MN_adword 0x13e5
#define MN_kxord 0x13ec
#define MN_vpxord 0x13f2
#define MN_pinsrd (MN_vpinsrd + 1)
#define MN_vpinsrd 0x13f9
#define MN_kshiftrd 0x1401
#define MN_pextrd (MN_vpextrd + 1)
#define MN_vpextrd 0x140a
#define MN_vfmsub231sd 0x1412
#define MN_vfnmsub231sd 0x141e
#define MN_vfmadd231sd 0x142b
#define MN_vfnmadd231sd 0x1437
#define MN_vfmsub132sd 0x1444
#define MN_vfnmsub132sd 0x1450
#define MN_vfmadd132sd 0x145d
#define MN_vfnmadd132sd 0x1469
#define MN_vcvtsh2sd 0x1476
#define MN_cvtsi2sd (MN_vcvtsi2sd + 1)
#define MN_vcvtsi2sd 0x1480
#define MN_vcvtusi2sd 0x148a
#define MN_cvtss2sd (MN_vcvtss2sd + 1)
#define MN_vcvtss2sd 0x1495
#define MN_vfmsub213sd 0x149f
#define MN_vfnmsub213sd 0x14ab
#define MN_vfmadd213sd 0x14b8
#define MN_vfnmadd213sd 0x14c4
#define MN_vrcp14sd 0x14d1
#define MN_vrsqrt14sd 0x14da
#define MN_vrcp28sd 0x14e5
#define MN_vrsqrt28sd 0x14ee
#define MN_pabsd (MN_vpabsd + 1)
#define MN_vpabsd 0x14f9
#define MN_subsd (MN_vfmsubsd + 3)
#define MN_vfmsubsd 0x1500
#define MN_vfnmsubsd 0x1509
#define MN_vsubsd 0x1513
#define MN_addsd (MN_vfmaddsd + 3)
#define MN_vfmaddsd 0x151a
#define MN_vfnmaddsd 0x1523
#define MN_vaddsd 0x152d
#define MN_roundsd (MN_vroundsd + 1)
#define MN_vroundsd 0x1534
#define MN_cmpunordsd (MN_vcmpunordsd + 1)
#define MN_vcmpunordsd 0x153d
#define MN_cmpordsd (MN_vcmpordsd + 1)
#define MN_vcmpordsd 0x1549
#define MN_vreducesd 0x1553
#define MN_vrangesd 0x155d
#define MN_vcmpngesd 0x1566
#define MN_vcmpgesd 0x1570
#define MN_vrndscalesd 0x1579
#define MN_cmpnlesd (MN_vcmpnlesd + 1)
#define MN_vcmpnlesd 0x1585
#define MN_cmplesd (MN_vcmplesd + 1)
#define MN_vcmplesd 0x158f
#define MN_vcmpfalsesd 0x1598
#define MN_vcmptruesd 0x15a4
#define MN_vscalefsd 0x15af
#define MN_comisd (MN_ucomisd + 1)
#define MN_ucomisd (MN_vucomisd + 1)
#define MN_vucomisd 0x15b9
#define MN_vcomisd 0x15c2
#define MN_mulsd (MN_vmulsd + 1)
#define MN_vmulsd 0x15ca
#define MN_vfixupimmsd 0x15d1
#define MN_minsd (MN_pminsd + 1)
#define MN_pminsd (MN_vpminsd + 1)
#define MN_vpminsd 0x15dd
#define MN_vminsd 0x15e5
#define MN_cmpsd (MN_vcmpsd + 1)
#define MN_vcmpsd 0x15ec
#define MN_vgetexpsd 0x15f3
#define MN_vcmpunord_qsd 0x15fd
#define MN_vcmpord_qsd 0x160b
#define MN_cmpneqsd (MN_vcmpneqsd + 1)
#define MN_vcmpneqsd 0x1617
#define MN_cmpeqsd (MN_vcmpeqsd + 1)
#define MN_vcmpeqsd 0x1621
#define MN_vcmpge_oqsd 0x162a
#define MN_vcmple_oqsd 0x1636
#define MN_vcmpfalse_oqsd 0x1642
#define MN_vcmpneq_oqsd 0x1651
#define MN_vcmpeq_oqsd 0x165e
#define MN_vcmpgt_oqsd 0x166a
#define MN_vcmplt_oqsd 0x1676
#define MN_vcmpnge_uqsd 0x1682
#define MN_vcmpnle_uqsd 0x168f
#define MN_vcmptrue_uqsd 0x169c
#define MN_vcmpneq_uqsd 0x16aa
#define MN_vcmpeq_uqsd 0x16b7
#define MN_vcmpngt_uqsd 0x16c3
#define MN_vcmpnlt_uqsd 0x16d0
#define MN_vcmpunord_ssd 0x16dd
#define MN_vcmpord_ssd 0x16eb
#define MN_vpdpbssd 0x16f7
#define MN_tdpbssd 0x1700
#define MN_vpcompressd 0x1708
#define MN_vcmpge_ossd 0x1714
#define MN_vcmple_ossd 0x1720
#define MN_vcmpfalse_ossd 0x172c
#define MN_vcmpneq_ossd 0x173b
#define MN_vcmpeq_ossd 0x1748
#define MN_vcmpgt_ossd 0x1754
#define MN_vcmplt_ossd 0x1760
#define MN_wrssd 0x176c
#define MN_vfpclasssd 0x1772
#define MN_vcmpnge_ussd 0x177d
#define MN_vcmpnle_ussd 0x178a
#define MN_vcmptrue_ussd 0x1797
#define MN_vcmpneq_ussd 0x17a5
#define MN_vcmpeq_ussd 0x17b2
#define MN_vcmpngt_ussd 0x17be
#define MN_vcmpnlt_ussd 0x17cb
#define MN_wrussd 0x17d8
#define MN_vp4dpwssd 0x17df
#define MN_vpdpwssd 0x17e9
#define MN_vcmpngtsd 0x17f2
#define MN_vcmpgtsd 0x17fc
#define MN_cmpnltsd (MN_vcmpnltsd + 1)
#define MN_vcmpnltsd 0x1805
#define MN_cmpltsd (MN_vcmpltsd + 1)
#define MN_vcmpltsd 0x180f
#define MN_vgetmantsd 0x1818
#define MN_movntsd 0x1823
#define MN_sqrtsd (MN_vsqrtsd + 1)
#define MN_vsqrtsd 0x182b
#define MN_vbroadcastsd 0x1833
#define MN_vpdpbusd 0x1840
#define MN_tdpbusd 0x1849
#define MN_vpdpwusd 0x1851
#define MN_divsd (MN_vdivsd + 1)
#define MN_vdivsd 0x185a
#define MN_movsd (MN_vmovsd + 1)
#define MN_vmovsd 0x1861
#define MN_maxsd (MN_pmaxsd + 1)
#define MN_pmaxsd (MN_vpmaxsd + 1)
#define MN_vpmaxsd 0x1868
#define MN_vmaxsd 0x1870
#define MN_vfrczsd 0x1877
#define MN_vp2intersectd 0x187f
#define MN_vpconflictd 0x188d
#define MN_vpcomgtd 0x1899
#define MN_pcmpgtd (MN_vpcmpgtd + 1)
#define MN_vpcmpgtd 0x18a2
#define MN_cltd 0x18ab
#define MN_vpcomltd 0x18b0
#define MN_vpcmpnltd 0x18b9
#define MN_vpcmpltd 0x18c3
#define MN_vpopcntd 0x18cc
#define MN_vplzcntd 0x18d5
#define MN_knotd 0x18de
#define MN_vprotd 0x18e4
#define MN_std (MN_vpbroadcastd + 9)
#define MN_vpbroadcastd 0x18eb
#define MN_ktestd 0x18f8
#define MN_kortestd 0x18ff
#define MN_cwtd 0x1908
#define MN_vpcomgeud 0x190d
#define MN_vpcomleud 0x1917
#define MN_vpcmpnleud 0x1921
#define MN_vpcmpleud 0x192c
#define MN_vpcomfalseud 0x1936
#define MN_vpcomtrueud 0x1943
#define MN_vpcomud 0x194f
#define MN_pminud (MN_vpminud + 1)
#define MN_vpminud 0x1957
#define MN_vpcmpud 0x195f
#define MN_vpcomequd 0x1967
#define MN_vpcomnequd 0x1971
#define MN_vpcmpnequd 0x197c
#define MN_vpcmpequd 0x1987
#define MN_vpdpbsud 0x1991
#define MN_tdpbsud 0x199a
#define MN_vpdpwsud 0x19a2
#define MN_vpcomgtud 0x19ab
#define MN_vpcomltud 0x19b5
#define MN_vpcmpnltud 0x19bf
#define MN_vpcmpltud 0x19ca
#define MN_vpdpbuud 0x19d4
#define MN_tdpbuud 0x19dd
#define MN_vpdpwuud 0x19e5
#define MN_pmaxud (MN_vpmaxud + 1)
#define MN_vpmaxud 0x19ee
#define MN_vpsravd 0x19f6
#define MN_vpshldvd 0x19fe
#define MN_vpshrdvd 0x1a07
#define MN_vpsllvd 0x1a10
#define MN_vprolvd 0x1a18
#define MN_vpsrlvd 0x1a20
#define MN_invd (MN_wbinvd + 2)
#define MN_wbinvd 0x1a28
#define MN_wbnoinvd 0x1a2f
#define MN_movd (MN_kmovd + 1)
#define MN_kmovd (MN_vpmaskmovd + 5)
#define MN_vpmaskmovd 0x1a38
#define MN_vmovd 0x1a43
#define MN_vprorvd 0x1a49
#define MN_vphsubwd 0x1a51
#define MN_cwd 0x1a5a
#define MN_vphaddwd 0x1a5e
#define MN_pmaddwd (MN_vpmaddwd + 1)
#define MN_vpmaddwd 0x1a67
#define MN_punpckhwd (MN_vpunpckhwd + 1)
#define MN_vpunpckhwd 0x1a70
#define MN_kunpckwd 0x1a7b
#define MN_punpcklwd (MN_vpunpcklwd + 1)
#define MN_vpunpcklwd 0x1a84
#define MN_vpmacswd 0x1a8f
#define MN_vpmadcswd 0x1a98
#define MN_vpmacsswd 0x1aa2
#define MN_vpmadcsswd 0x1aac
#define MN_vphadduwd 0x1ab7
#define MN_pmovsxwd (MN_vpmovsxwd + 1)
#define MN_vpmovsxwd 0x1ac1
#define MN_pmovzxwd (MN_vpmovzxwd + 1)
#define MN_vpmovzxwd 0x1acb
#define MN_movsxd 0x1ad5
#define MN_fldl2e 0x1adc
#define MN_jae 0x1ae3
#define MN_jnae 0x1ae7
#define MN_setnae 0x1aec
#define MN_cmovnae (MN_fcmovnae + 1)
#define MN_fcmovnae 0x1af3
#define MN_setae 0x1afc
#define MN_cmovae (MN_fcmovae + 1)
#define MN_fcmovae 0x1b02
#define MN_jbe 0x1b0a
#define MN_jnbe 0x1b0e
#define MN_setnbe 0x1b13
#define MN_cmovnbe (MN_fcmovnbe + 1)
#define MN_fcmovnbe 0x1b1a
#define MN_setbe 0x1b23
#define MN_movbe (MN_cmovbe + 1)
#define MN_cmovbe (MN_fcmovbe + 1)
#define MN_fcmovbe 0x1b29
#define MN_lfence 0x1b31
#define MN_mfence 0x1b38
#define MN_sfence 0x1b3f
#define MN_cwde 0x1b46
#define MN_ffree 0x1b4b
#define MN_jge 0x1b51
#define MN_jnge 0x1b55
#define MN_setnge 0x1b5a
#define MN_cmovnge 0x1b61
#define MN_pfcmpge 0x1b69
#define MN_setge 0x1b71
#define MN_cmovge 0x1b77
#define MN_je 0x1b7e
#define MN_fscale 0x1b81
#define MN_jle 0x1b88
#define MN_jnle 0x1b8c
#define MN_setnle 0x1b91
#define MN_cmovnle 0x1b98
#define MN_setle 0x1ba0
#define MN_cmovle 0x1ba6
#define MN_vmresume 0x1bad
#define MN_jne 0x1bb6
#define MN_repne 0x1bba
#define MN_loopne 0x1bc0
#define MN_setne 0x1bc7
#define MN_cmovne (MN_fcmovne + 1)
#define MN_fcmovne 0x1bcd
#define MN_repe 0x1bd5
#define MN_jpe 0x1bda
#define MN_loope 0x1bde
#define MN_setpe 0x1be4
#define MN_cmovpe 0x1bea
#define MN_cdqe 0x1bf1
#define MN_xacquire 0x1bf6
#define MN_xstore 0x1bff
#define MN_rdfsbase 0x1c06
#define MN_wrfsbase 0x1c0f
#define MN_rdgsbase 0x1c18
#define MN_wrgsbase 0x1c21
#define MN_tilerelease 0x1c2a
#define MN_xrelease 0x1c36
#define MN_pause (MN_tpause + 1)
#define MN_tpause 0x1c3f
#define MN_pvalidate 0x1c46
#define MN_rmpupdate 0x1c50
#define MN_sete 0x1c5a
#define MN_vmwrite 0x1c5f
#define MN_ptwrite 0x1c67
#define MN_cldemote 0x1c6f
#define MN_sha1nexte 0x1c78
#define MN_leave 0x1c82
#define MN_fsave 0x1c88
#define MN_vmsave 0x1c8e
#define MN_fnsave 0x1c95
#define MN_xsave (MN_fxsave + 1)
#define MN_fxsave 0x1c9c
#define MN_cmove (MN_fcmove + 1)
#define MN_fcmove 0x1ca3
#define MN_serialize 0x1caa
#define MN_vmxoff 0x1cb4
#define MN_lahf 0x1cbb
#define MN_sahf 0x1cc0
#define MN_pushf 0x1cc5
#define MN_popf 0x1ccb
#define MN_bsf 0x1cd0
#define MN_retf 0x1cd4
#define MN_neg 0x1cd9
#define MN_ldtilecfg 0x1cdd
#define MN_sttilecfg 0x1ce7
#define MN_xchg (MN_cmpxchg + 3)
#define MN_cmpxchg 0x1cf1
#define MN_pconfig 0x1cf9
#define MN_jg 0x1d01
#define MN_jng 0x1d04
#define MN_xstore_rng 0x1d08
#define MN_xstorerng 0x1d13
#define MN_setng 0x1d1d
#define MN_cmovng 0x1d23
#define MN_invlpg 0x1d2a
#define MN_setg 0x1d31
#define MN_cmovg 0x1d36
#define MN_vmlaunch 0x1d3c
#define MN_prefetch 0x1d45
#define MN_fxch 0x1d4e
#define MN_vfmaddsub231ph 0x1d53
#define MN_vfmsub231ph 0x1d62
#define MN_vfnmsub231ph 0x1d6e
#define MN_vfmsubadd231ph 0x1d7b
#define MN_vfmadd231ph 0x1d8a
#define MN_vfnmadd231ph 0x1d96
#define MN_vfmaddsub132ph 0x1da3
#define MN_vfmsub132ph 0x1db2
#define MN_vfnmsub132ph 0x1dbe
#define MN_vfmsubadd132ph 0x1dcb
#define MN_vfmadd132ph 0x1dda
#define MN_vfnmadd132ph 0x1de6
#define MN_vcvtpd2ph 0x1df3
#define MN_vcvtdq2ph 0x1dfd
#define MN_vcvtudq2ph 0x1e07
#define MN_vcvtqq2ph 0x1e12
#define MN_vcvtuqq2ph 0x1e1c
#define MN_vcvtps2ph 0x1e27
#define MN_vcvtw2ph 0x1e31
#define MN_vcvtuw2ph 0x1e3a
#define MN_vfmaddsub213ph 0x1e44
#define MN_vfmsub213ph 0x1e53
#define MN_vfnmsub213ph 0x1e5f
#define MN_vfmsubadd213ph 0x1e6c
#define MN_vfmadd213ph 0x1e7b
#define MN_vfnmadd213ph 0x1e87
#define MN_vsubph 0x1e94
#define MN_vfcmaddcph 0x1e9b
#define MN_vfmaddcph 0x1ea6
#define MN_vfcmulcph 0x1eb0
#define MN_vfmulcph 0x1eba
#define MN_vaddph 0x1ec3
#define MN_vcmpunordph 0x1eca
#define MN_vcmpordph 0x1ed6
#define MN_vreduceph 0x1ee0
#define MN_vcmpngeph 0x1eea
#define MN_vcmpgeph 0x1ef4
#define MN_vrndscaleph 0x1efd
#define MN_vcmpnleph 0x1f09
#define MN_vcmpleph 0x1f13
#define MN_vcmpfalseph 0x1f1c
#define MN_vcmptrueph 0x1f28
#define MN_vscalefph 0x1f33
#define MN_vmulph 0x1f3d
#define MN_vminph 0x1f44
#define MN_vrcpph 0x1f4b
#define MN_vcmpph 0x1f52
#define MN_vgetexpph 0x1f59
#define MN_vcmpunord_qph 0x1f63
#define MN_vcmpord_qph 0x1f71
#define MN_vcmpneqph 0x1f7d
#define MN_vcmpeqph 0x1f87
#define MN_vcmpge_oqph 0x1f90
#define MN_vcmple_oqph 0x1f9c
#define MN_vcmpfalse_oqph 0x1fa8
#define MN_vcmpneq_oqph 0x1fb7
#define MN_vcmpeq_oqph 0x1fc4
#define MN_vcmpgt_oqph 0x1fd0
#define MN_vcmplt_oqph 0x1fdc
#define MN_vcmpnge_uqph 0x1fe8
#define MN_vcmpnle_uqph 0x1ff5
#define MN_vcmptrue_uqph 0x2002
#define MN_vcmpneq_uqph 0x2010
#define MN_vcmpeq_uqph 0x201d
#define MN_vcmpngt_uqph 0x2029
#define MN_vcmpnlt_uqph 0x2036
#define MN_vcmpunord_sph 0x2043
#define MN_vcmpord_sph 0x2051
#define MN_vcmpge_osph 0x205d
#define MN_vcmple_osph 0x2069
#define MN_vcmpfalse_osph 0x2075
#define MN_vcmpneq_osph 0x2084
#define MN_vcmpeq_osph 0x2091
#define MN_vcmpgt_osph 0x209d
#define MN_vcmplt_osph 0x20a9
#define MN_vfpclassph 0x20b5
#define MN_vcmpnge_usph 0x20c0
#define MN_vcmpnle_usph 0x20cd
#define MN_vcmptrue_usph 0x20da
#define MN_vcmpneq_usph 0x20e8
#define MN_vcmpeq_usph 0x20f5
#define MN_vcmpngt_usph 0x2101
#define MN_vcmpnlt_usph 0x210e
#define MN_vcmpngtph 0x211b
#define MN_vcmpgtph 0x2125
#define MN_vcmpnltph 0x212e
#define MN_vcmpltph 0x2138
#define MN_vgetmantph 0x2141
#define MN_vrsqrtph 0x214c
#define MN_vsqrtph 0x2155
#define MN_vdivph 0x215d
#define MN_vmaxph 0x2164
#define MN_vpmacsdqh 0x216b
#define MN_vpmacssdqh 0x2175
#define MN_vfmsub231sh 0x2180
#define MN_vfnmsub231sh 0x218c
#define MN_vfmadd231sh 0x2199
#define MN_vfnmadd231sh 0x21a5
#define MN_vfmsub132sh 0x21b2
#define MN_vfnmsub132sh 0x21be
#define MN_vfmadd132sh 0x21cb
#define MN_vfnmadd132sh 0x21d7
#define MN_vcvtsd2sh 0x21e4
#define MN_vcvtsi2sh 0x21ee
#define MN_vcvtusi2sh 0x21f8
#define MN_vcvtss2sh 0x2203
#define MN_vfmsub213sh 0x220d
#define MN_vfnmsub213sh 0x2219
#define MN_vfmadd213sh 0x2226
#define MN_vfnmadd213sh 0x2232
#define MN_psmash 0x223f
#define MN_vsubsh 0x2246
#define MN_vfcmaddcsh 0x224d
#define MN_vfmaddcsh 0x2258
#define MN_vfcmulcsh 0x2262
#define MN_vfmulcsh 0x226c
#define MN_vaddsh 0x2275
#define MN_vcmpunordsh 0x227c
#define MN_vcmpordsh 0x2288
#define MN_vreducesh 0x2292
#define MN_vcmpngesh 0x229c
#define MN_vcmpgesh 0x22a6
#define MN_vrndscalesh 0x22af
#define MN_vcmpnlesh 0x22bb
#define MN_vcmplesh 0x22c5
#define MN_vcmpfalsesh 0x22ce
#define MN_vcmptruesh 0x22da
#define MN_vscalefsh 0x22e5
#define MN_vucomish 0x22ef
#define MN_vcomish 0x22f8
#define MN_vmulsh 0x2300
#define MN_vminsh 0x2307
#define MN_vrcpsh 0x230e
#define MN_vcmpsh 0x2315
#define MN_vgetexpsh 0x231c
#define MN_vcmpunord_qsh 0x2326
#define MN_vcmpord_qsh 0x2334
#define MN_vcmpneqsh 0x2340
#define MN_vcmpeqsh 0x234a
#define MN_vcmpge_oqsh 0x2353
#define MN_vcmple_oqsh 0x235f
#define MN_vcmpfalse_oqsh 0x236b
#define MN_vcmpneq_oqsh 0x237a
#define MN_vcmpeq_oqsh 0x2387
#define MN_vcmpgt_oqsh 0x2393
#define MN_vcmplt_oqsh 0x239f
#define MN_vcmpnge_uqsh 0x23ab
#define MN_vcmpnle_uqsh 0x23b8
#define MN_vcmptrue_uqsh 0x23c5
#define MN_vcmpneq_uqsh 0x23d3
#define MN_vcmpeq_uqsh 0x23e0
#define MN_vcmpngt_uqsh 0x23ec
#define MN_vcmpnlt_uqsh 0x23f9
#define MN_vcmpunord_ssh 0x2406
#define MN_vcmpord_ssh 0x2414
#define MN_vcmpge_ossh 0x2420
#define MN_vcmple_ossh 0x242c
#define MN_vcmpfalse_ossh 0x2438
#define MN_vcmpneq_ossh 0x2447
#define MN_vcmpeq_ossh 0x2454
#define MN_vcmpgt_ossh 0x2460
#define MN_vcmplt_ossh 0x246c
#define MN_vfpclasssh 0x2478
#define MN_vcmpnge_ussh 0x2483
#define MN_vcmpnle_ussh 0x2490
#define MN_vcmptrue_ussh 0x249d
#define MN_vcmpneq_ussh 0x24ab
#define MN_vcmpeq_ussh 0x24b8
#define MN_vcmpngt_ussh 0x24c4
#define MN_vcmpnlt_ussh 0x24d1
#define MN_vcmpngtsh 0x24de
#define MN_vcmpgtsh 0x24e8
#define MN_vcmpnltsh 0x24f1
#define MN_vcmpltsh 0x24fb
#define MN_vgetmantsh 0x2504
#define MN_vrsqrtsh 0x250f
#define MN_vsqrtsh 0x2518
#define MN_clflush 0x2520
#define MN_push 0x2528
#define MN_vdivsh 0x252d
#define MN_vmovsh 0x2534
#define MN_vmaxsh 0x253b
#define MN_blci 0x2542
#define MN_clgi 0x2547
#define MN_stgi 0x254c
#define MN_bzhi 0x2551
#define MN_cli 0x2556
#define MN_fcomi 0x255a
#define MN_fucomi 0x2560
#define MN_feni 0x2567
#define MN_fneni 0x256c
#define MN_cvttpd2pi 0x2572
#define MN_cvtpd2pi 0x257c
#define MN_cvttps2pi 0x2585
#define MN_cvtps2pi 0x258f
#define MN_fldpi 0x2598
#define MN_senduipi 0x259e
#define MN_fcompi 0x25a7
#define MN_fucompi 0x25ae
#define MN_movdiri 0x25b6
#define MN_pcmpestri (MN_vpcmpestri + 1)
#define MN_vpcmpestri 0x25be
#define MN_pcmpistri (MN_vpcmpistri + 1)
#define MN_vpcmpistri 0x25c9
#define MN_cvttsd2si (MN_vcvttsd2si + 1)
#define MN_vcvttsd2si 0x25d4
#define MN_cvtsd2si (MN_vcvtsd2si + 1)
#define MN_vcvtsd2si 0x25df
#define MN_vcvttsh2si 0x25e9
#define MN_vcvtsh2si 0x25f4
#define MN_cvttss2si (MN_vcvttss2si + 1)
#define MN_vcvttss2si 0x25fe
#define MN_cvtss2si (MN_vcvtss2si + 1)
#define MN_vcvtss2si 0x2609
#define MN_fdisi 0x2613
#define MN_fndisi 0x2619
#define MN_blsi 0x2620
#define MN_vcvttsd2usi 0x2625
#define MN_vcvtsd2usi 0x2631
#define MN_vcvttsh2usi 0x263c
#define MN_vcvtsh2usi 0x2648
#define MN_vcvttss2usi 0x2653
#define MN_vcvtss2usi 0x265f
#define MN_movnti 0x266a
#define MN_sti 0x2671
#define MN_clui 0x2675
#define MN_stui (MN_testui + 2)
#define MN_testui 0x267a
#define MN_notrack 0x2681
#define MN_lock 0x2689
#define MN_bndmk 0x268e
#define MN_xresldtrk 0x2694
#define MN_xsusldtrk 0x269e
#define MN_blcmsk 0x26a8
#define MN_blsmsk 0x26af
#define MN_tzmsk 0x26b6
#define MN_sal 0x26bc
#define MN_lwpval 0x26c0
#define MN_bndcl 0x26c7
#define MN_rcl 0x26cd
#define MN_shl 0x26d1
#define MN_jl 0x26d5
#define MN_aesdec256kl 0x26d8
#define MN_aesenc256kl 0x26e4
#define MN_aesdecwide256kl 0x26f0
#define MN_aesencwide256kl 0x2700
#define MN_aesdec128kl 0x2710
#define MN_aesenc128kl 0x271c
#define MN_aesdecwide128kl 0x2728
#define MN_aesencwide128kl 0x2738
#define MN_call (MN_tdcall + 2)
#define MN_tdcall 0x2748
#define MN_lcall 0x274f
#define MN_seamcall 0x2755
#define MN_vmmcall 0x275e
#define MN_vmcall 0x2766
#define MN_syscall 0x276d
#define MN_vzeroall 0x2775
#define MN_fildll 0x277e
#define MN_blcfill 0x2785
#define MN_blsfill 0x278d
#define MN_fistpll 0x2795
#define MN_fisttpll 0x279d
#define MN_jnl 0x27a6
#define MN_setnl 0x27aa
#define MN_cmovnl 0x27b0
#define MN_rol 0x27b7
#define MN_arpl 0x27bb
#define MN_vpmacsdql 0x27c0
#define MN_vpmacssdql 0x27ca
#define MN_lsl 0x27d5
#define MN_movsl 0x27d9
#define MN_setl 0x27df
#define MN_cwtl 0x27e4
#define MN_mul (MN_fmul + 1)
#define MN_fmul (MN_pfmul + 1)
#define MN_pfmul 0x27e9
#define MN_imul (MN_fimul + 1)
#define MN_fimul 0x27ef
#define MN_montmul 0x27f5
#define MN_cmovl 0x27fd
#define MN_vpmovb2m 0x2803
#define MN_vpmovd2m 0x280c
#define MN_vpmovq2m 0x2815
#define MN_vpmovw2m 0x281e
#define MN_aam 0x2827
#define MN_fxam 0x282b
#define MN_fprem 0x2830
#define MN_fcom 0x2836
#define MN_ficom 0x283b
#define MN_fucom 0x2841
#define MN_fsetpm 0x2847
#define MN_fnsetpm 0x284e
#define MN_frstpm 0x2856
#define MN_vpperm 0x285d
#define MN_pcmpestrm (MN_vpcmpestrm + 1)
#define MN_vpcmpestrm 0x2864
#define MN_pcmpistrm (MN_vpcmpistrm + 1)
#define MN_vpcmpistrm 0x286f
#define MN_rsm 0x287a
#define MN_fpatan 0x287e
#define MN_fptan 0x2885
#define MN_bndcn 0x288b
#define MN_andn (MN_pandn + 1)
#define MN_pandn (MN_vpandn + 1)
#define MN_vpandn 0x2891
#define MN_in (MN_xbegin + 4)
#define MN_xbegin 0x2898
#define MN_pfmin 0x289f
#define MN_fsin 0x28a5
#define MN_vmxon 0x28aa
#define MN_vmrun 0x28b0
#define MN_jo 0x28b6
#define MN_jno 0x28b9
#define MN_setno 0x28bd
#define MN_cmovno 0x28c3
#define MN_jpo 0x28ca
#define MN_setpo 0x28ce
#define MN_cmovpo 0x28d4
#define MN_cqo 0x28db
#define MN_tilezero 0x28df
#define MN_clzero 0x28e8
#define MN_seto 0x28ef
#define MN_into 0x28f4
#define MN_cqto 0x28f9
#define MN_ssto 0x28fe
#define MN_cmovo 0x2903
#define MN_push2p 0x2909
#define MN_pop2p 0x2910
#define MN_bswap 0x2916
#define MN_fsubp 0x291c
#define MN_pfrcp 0x2922
#define MN_rdtscp 0x2928
#define MN_faddp 0x292f
#define MN_pdep 0x2935
#define MN_ffreep 0x293a
#define MN_rep 0x2941
#define MN_pushp 0x2945
#define MN_fcomip 0x294b
#define MN_fucomip 0x2952
#define MN_jp 0x295a
#define MN_fmulp 0x295d
#define MN_cmp (MN_scmp + 1)
#define MN_scmp 0x2963
#define MN_jmp (MN_ljmp + 1)
#define MN_ljmp 0x2968
#define MN_fcomp 0x296d
#define MN_ficomp 0x2973
#define MN_fucomp 0x297a
#define MN_jnp 0x2981
#define MN_setnp 0x2985
#define MN_cmovnp 0x298b
#define MN_nop (MN_fnop + 1)
#define MN_fnop 0x2992
#define MN_loop 0x2997
#define MN_pop 0x299c
#define MN_fcompp 0x29a0
#define MN_fucompp 0x29a7
#define MN_popp 0x29af
#define MN_fsubrp 0x29b4
#define MN_fdivrp 0x29bb
#define MN_rstorssp 0x29c2
#define MN_saveprevssp 0x29cb
#define MN_setp 0x29d7
#define MN_fbstp 0x29dc
#define MN_fdecstp 0x29e2
#define MN_fincstp 0x29ea
#define MN_fstp 0x29f2
#define MN_fistp 0x29f7
#define MN_fisttp 0x29fd
#define MN_movddup (MN_vmovddup + 1)
#define MN_vmovddup 0x2a04
#define MN_movshdup (MN_vmovshdup + 1)
#define MN_vmovshdup 0x2a0d
#define MN_movsldup (MN_vmovsldup + 1)
#define MN_vmovsldup 0x2a17
#define MN_fdivp 0x2a21
#define MN_cmovp 0x2a27
#define MN_vpbroadcastmb2q 0x2a2d
#define MN_vpermi2q 0x2a3d
#define MN_vpmovm2q 0x2a46
#define MN_movdq2q 0x2a4f
#define MN_vpermt2q 0x2a57
#define MN_vpshaq 0x2a60
#define MN_vpsraq 0x2a67
#define MN_vphaddbq 0x2a6e
#define MN_vphaddubq 0x2a77
#define MN_psubq (MN_vpsubq + 1)
#define MN_vpsubq 0x2a81
#define MN_pmovsxbq (MN_vpmovsxbq + 1)
#define MN_vpmovsxbq 0x2a88
#define MN_pmovzxbq (MN_vpmovzxbq + 1)
#define MN_vpmovzxbq 0x2a92
#define MN_cvttpd2dq (MN_vcvttpd2dq + 1)
#define MN_vcvttpd2dq 0x2a9c
#define MN_cvtpd2dq (MN_vcvtpd2dq + 1)
#define MN_vcvtpd2dq 0x2aa7
#define MN_vcvttph2dq 0x2ab1
#define MN_vcvtph2dq 0x2abc
#define MN_movq2dq 0x2ac6
#define MN_cvttps2dq (MN_vcvttps2dq + 1)
#define MN_vcvttps2dq 0x2ace
#define MN_cvtps2dq (MN_vcvtps2dq + 1)
#define MN_vcvtps2dq 0x2ad9
#define MN_vphsubdq 0x2ae3
#define MN_cdq 0x2aec
#define MN_kaddq 0x2af0
#define MN_paddq (MN_vpaddq + 1)
#define MN_vpaddq 0x2af6
#define MN_vphadddq 0x2afd
#define MN_punpckhdq (MN_vpunpckhdq + 1)
#define MN_vpunpckhdq 0x2b06
#define MN_kunpckdq 0x2b11
#define MN_vpshldq 0x2b1a
#define MN_punpckldq (MN_vpunpckldq + 1)
#define MN_vpunpckldq 0x2b22
#define MN_pslldq (MN_vpslldq + 1)
#define MN_vpslldq 0x2b2d
#define MN_psrldq (MN_vpsrldq + 1)
#define MN_vpsrldq 0x2b35
#define MN_pmuldq (MN_vpmuldq + 1)
#define MN_vpmuldq 0x2b3d
#define MN_kandq 0x2b45
#define MN_vpandq 0x2b4b
#define MN_vpexpandq 0x2b52
#define MN_punpckhqdq (MN_vpunpckhqdq + 1)
#define MN_vpunpckhqdq 0x2b5c
#define MN_pclmulhqhqdq (MN_vpclmulhqhqdq + 1)
#define MN_vpclmulhqhqdq 0x2b68
#define MN_pclmullqhqdq (MN_vpclmullqhqdq + 1)
#define MN_vpclmullqhqdq 0x2b76
#define MN_punpcklqdq (MN_vpunpcklqdq + 1)
#define MN_vpunpcklqdq 0x2b84
#define MN_pclmulhqlqdq (MN_vpclmulhqlqdq + 1)
#define MN_vpclmulhqlqdq 0x2b90
#define MN_pclmullqlqdq (MN_vpclmullqlqdq + 1)
#define MN_vpclmullqlqdq 0x2b9e
#define MN_pclmulqdq (MN_vpclmulqdq + 1)
#define MN_vpclmulqdq 0x2bac
#define MN_vpgatherdq 0x2bb7
#define MN_vpscatterdq 0x2bc2
#define MN_vpshrdq 0x2bce
#define MN_movntdq (MN_vmovntdq + 1)
#define MN_vmovntdq 0x2bd6
#define MN_vcvttpd2udq 0x2bdf
#define MN_vcvtpd2udq 0x2beb
#define MN_vcvttph2udq 0x2bf6
#define MN_vcvtph2udq 0x2c02
#define MN_vcvttps2udq 0x2c0d
#define MN_vcvtps2udq 0x2c19
#define MN_vphaddudq 0x2c24
#define MN_pmuludq (MN_vpmuludq + 1)
#define MN_vpmuludq 0x2c2e
#define MN_pmovsxdq (MN_vpmovsxdq + 1)
#define MN_vpmovsxdq 0x2c37
#define MN_pmovzxdq (MN_vpmovzxdq + 1)
#define MN_vpmovzxdq 0x2c41
#define MN_vpcomgeq 0x2c4b
#define MN_vpcomleq 0x2c54
#define MN_vpcmpnleq 0x2c5d
#define MN_vpcmpleq 0x2c67
#define MN_pfcmpeq 0x2c70
#define MN_vpcomfalseq 0x2c78
#define MN_vpcomtrueq 0x2c84
#define MN_vpternlogq 0x2c8f
#define MN_vpshlq 0x2c9a
#define MN_psllq (MN_vpsllq + 1)
#define MN_vpsllq 0x2ca1
#define MN_vpmullq 0x2ca8
#define MN_vprolq 0x2cb0
#define MN_psrlq (MN_vpsrlq + 1)
#define MN_vpsrlq 0x2cb7
#define MN_kshiftlq 0x2cbe
#define MN_vpblendmq 0x2cc7
#define MN_vptestnmq 0x2cd1
#define MN_vpcomq 0x2cdb
#define MN_vpermq 0x2ce2
#define MN_vptestmq 0x2ce9
#define MN_kandnq 0x2cf2
#define MN_vpandnq 0x2cf9
#define MN_valignq 0x2d01
#define MN_vpcmpq 0x2d09
#define MN_incsspq 0x2d10
#define MN_rdsspq 0x2d18
#define MN_vcvttpd2qq 0x2d1f
#define MN_vcvtpd2qq 0x2d2a
#define MN_vcvttph2qq 0x2d34
#define MN_vcvtph2qq 0x2d3f
#define MN_vcvttps2qq 0x2d49
#define MN_vcvtps2qq 0x2d54
#define MN_vpcomeqq 0x2d5e
#define MN_vpcomneqq 0x2d67
#define MN_vpcmpneqq 0x2d71
#define MN_pcmpeqq (MN_vpcmpeqq + 1)
#define MN_vpcmpeqq 0x2d7b
#define MN_vpgatherqq 0x2d84
#define MN_vpscatterqq 0x2d8f
#define MN_vcvttpd2uqq 0x2d9b
#define MN_vcvtpd2uqq 0x2da7
#define MN_vcvttph2uqq 0x2db2
#define MN_vcvtph2uqq 0x2dbe
#define MN_vcvttps2uqq 0x2dc9
#define MN_vcvtps2uqq 0x2dd5
#define MN_korq 0x2de0
#define MN_kxnorq 0x2de5
#define MN_vporq 0x2dec
#define MN_vprorq 0x2df2
#define MN_kxorq 0x2df9
#define MN_vpxorq 0x2dff
#define MN_pinsrq (MN_vpinsrq + 1)
#define MN_vpinsrq 0x2e06
#define MN_kshiftrq 0x2e0e
#define MN_extrq (MN_pextrq + 1)
#define MN_pextrq (MN_vpextrq + 1)
#define MN_vpextrq 0x2e17
#define MN_vpabsq 0x2e1f
#define MN_vpminsq 0x2e26
#define MN_vpcompressq 0x2e2e
#define MN_wrssq 0x2e3a
#define MN_wrussq 0x2e40
#define MN_vpmaxsq 0x2e47
#define MN_vp2intersectq 0x2e4f
#define MN_vpconflictq 0x2e5d
#define MN_vpcomgtq 0x2e69
#define MN_pcmpgtq (MN_vpcmpgtq + 1)
#define MN_vpcmpgtq 0x2e72
#define MN_cltq 0x2e7b
#define MN_vpcomltq 0x2e80
#define MN_vpcmpnltq 0x2e89
#define MN_vpcmpltq 0x2e93
#define MN_vpopcntq 0x2e9c
#define MN_vplzcntq 0x2ea5
#define MN_movntq 0x2eae
#define MN_knotq 0x2eb5
#define MN_vprotq 0x2ebb
#define MN_insertq 0x2ec2
#define MN_vpbroadcastq 0x2eca
#define MN_ktestq 0x2ed7
#define MN_kortestq 0x2ede
#define MN_vpcomgeuq 0x2ee7
#define MN_vpcomleuq 0x2ef1
#define MN_vpcmpnleuq 0x2efb
#define MN_vpcmpleuq 0x2f06
#define MN_vpcomfalseuq 0x2f10
#define MN_vpcomtrueuq 0x2f1d
#define MN_vpmadd52huq 0x2f29
#define MN_vpmadd52luq 0x2f35
#define MN_vpcomuq 0x2f41
#define MN_vpminuq 0x2f49
#define MN_vpcmpuq 0x2f51
#define MN_vpcomequq 0x2f59
#define MN_vpcomnequq 0x2f63
#define MN_vpcmpnequq 0x2f6e
#define MN_vpcmpequq 0x2f79
#define MN_vpcomgtuq 0x2f83
#define MN_vpcomltuq 0x2f8d
#define MN_vpcmpnltuq 0x2f97
#define MN_vpcmpltuq 0x2fa2
#define MN_vpmaxuq 0x2fac
#define MN_vpsravq 0x2fb4
#define MN_vpshldvq 0x2fbc
#define MN_vpshrdvq 0x2fc5
#define MN_vpsllvq 0x2fce
#define MN_vprolvq 0x2fd6
#define MN_vpsrlvq 0x2fde
#define MN_movq (MN_kmovq + 1)
#define MN_kmovq (MN_maskmovq + 3)
#define MN_maskmovq (MN_vpmaskmovq + 2)
#define MN_vpmaskmovq 0x2fe6
#define MN_vmovq 0x2ff1
#define MN_vprorvq 0x2ff7
#define MN_vphaddwq 0x2fff
#define MN_vphadduwq 0x3008
#define MN_pmovsxwq (MN_vpmovsxwq + 1)
#define MN_vpmovsxwq 0x3012
#define MN_pmovzxwq (MN_vpmovzxwq + 1)
#define MN_vpmovzxwq 0x301c
#define MN_rex_r 0x3026
#define MN_vmclear 0x302c
#define MN_lar 0x3034
#define MN_sar 0x3038
#define MN_fsubr (MN_pfsubr + 1)
#define MN_pfsubr 0x303c
#define MN_fisubr 0x3043
#define MN_rcr 0x304a
#define MN_vzeroupper 0x304e
#define MN_enter (MN_sysenter + 3)
#define MN_sysenter 0x3059
#define MN_shr 0x3062
#define MN_clr 0x3066
#define MN_palignr (MN_vpalignr + 1)
#define MN_vpalignr 0x306a
#define MN_or (MN_aor + 1)
#define MN_aor 0x3073
#define MN_por (MN_vpor + 1)
#define MN_vpor 0x3077
#define MN_ror 0x307c
#define MN_monitor (MN_umonitor + 1)
#define MN_umonitor 0x3080
#define MN_frstor 0x3089
#define MN_xrstor (MN_fxrstor + 1)
#define MN_fxrstor 0x3090
#define MN_xor (MN_axor + 1)
#define MN_axor 0x3098
#define MN_pxor (MN_vpxor + 1)
#define MN_vpxor 0x309d
#define MN_verr 0x30a3
#define MN_bsr 0x30a8
#define MN_ldmxcsr (MN_vldmxcsr + 1)
#define MN_vldmxcsr 0x30ac
#define MN_stmxcsr (MN_vstmxcsr + 1)
#define MN_vstmxcsr 0x30b5
#define MN_blsr 0x30be
#define MN_rdmsr (MN_urdmsr + 1)
#define MN_urdmsr 0x30c3
#define MN_wrmsr (MN_uwrmsr + 1)
#define MN_uwrmsr 0x30ca
#define MN_btr 0x30d1
#define MN_xcrypt_ctr 0x30d5
#define MN_xcryptctr 0x30e0
#define MN_ltr 0x30ea
#define MN_str 0x30ee
#define MN_bextr 0x30f2
#define MN_fdivr 0x30f8
#define MN_fidivr 0x30fe
#define MN_rex_wr 0x3105
#define MN_aas 0x310c
#define MN_scas 0x3110
#define MN_das 0x3115
#define MN_fabs 0x3119
#define MN_movabs 0x311e
#define MN_cs (MN_blcs + 2)
#define MN_blcs 0x3125
#define MN_ds (MN_lds + 1)
#define MN_lds 0x312a
#define MN_enqcmds 0x312e
#define MN_lods 0x3136
#define MN_vpdpbssds 0x313b
#define MN_vp4dpwssds 0x3145
#define MN_vpdpwssds 0x3150
#define MN_vpdpbusds 0x315a
#define MN_vpdpwusds 0x3164
#define MN_vpdpbsuds 0x316e
#define MN_vpdpwsuds 0x3178
#define MN_vpdpbuuds 0x3182
#define MN_vpdpwuuds 0x318c
#define MN_es (MN_les + 1)
#define MN_les 0x3196
#define MN_xsaves 0x319a
#define MN_fs (MN_lfs + 1)
#define MN_lfs 0x31a1
#define MN_gs (MN_lkgs + 2)
#define MN_lkgs 0x31a5
#define MN_lgs 0x31aa
#define MN_swapgs 0x31ae
#define MN_fchs 0x31b5
#define MN_js 0x31ba
#define MN_encls 0x31bd
#define MN_emms (MN_femms + 1)
#define MN_femms 0x31c3
#define MN_ins (MN_lwpins + 3)
#define MN_lwpins 0x31c9
#define MN_jns 0x31d0
#define MN_wrmsrns 0x31d4
#define MN_setns 0x31dc
#define MN_cmovns 0x31e2
#define MN_fcos 0x31e9
#define MN_fsincos 0x31ee
#define MN_stos 0x31f6
#define MN_vfmaddsub231ps 0x31fb
#define MN_vfmsub231ps 0x320a
#define MN_vfnmsub231ps 0x3216
#define MN_vfmsubadd231ps 0x3223
#define MN_vfmadd231ps 0x3232
#define MN_vfnmadd231ps 0x323e
#define MN_vfmaddsub132ps 0x324b
#define MN_vfmsub132ps 0x325a
#define MN_vfnmsub132ps 0x3266
#define MN_vfmsubadd132ps 0x3273
#define MN_vfmadd132ps 0x3282
#define MN_vfnmadd132ps 0x328e
#define MN_vcvtneebf162ps 0x329b
#define MN_vbcstnebf162ps 0x32aa
#define MN_vcvtneobf162ps 0x32b9
#define MN_cvtpd2ps (MN_vcvtpd2ps + 1)
#define MN_vcvtpd2ps 0x32c8
#define MN_vcvtneeph2ps 0x32d2
#define MN_vcvtneoph2ps 0x32df
#define MN_vcvtph2ps 0x32ec
#define MN_vbcstnesh2ps 0x32f6
#define MN_vpermi2ps 0x3303
#define MN_cvtpi2ps 0x330d
#define MN_vpermil2ps 0x3316
#define MN_vexp2ps 0x3321
#define MN_cvtdq2ps (MN_vcvtdq2ps + 1)
#define MN_vcvtdq2ps 0x3329
#define MN_vcvtudq2ps 0x3333
#define MN_vcvtqq2ps 0x333e
#define MN_vcvtuqq2ps 0x3348
#define MN_vpermt2ps 0x3353
#define MN_vfmaddsub213ps 0x335d
#define MN_vfmsub213ps 0x336c
#define MN_vfnmsub213ps 0x3378
#define MN_vfmsubadd213ps 0x3385
#define MN_vfmadd213ps 0x3394
#define MN_vfnmadd213ps 0x33a0
#define MN_vrcp14ps 0x33ad
#define MN_vrsqrt14ps 0x33b6
#define MN_tdpbf16ps 0x33c1
#define MN_vdpbf16ps 0x33cb
#define MN_tcmmrlfp16ps 0x33d5
#define MN_tcmmimfp16ps 0x33e2
#define MN_tdpfp16ps 0x33ef
#define MN_vrcp28ps 0x33f9
#define MN_vrsqrt28ps 0x3402
#define MN_movaps (MN_vmovaps + 1)
#define MN_vmovaps 0x340d
#define MN_subps (MN_addsubps + 3)
#define MN_addsubps (MN_vfmaddsubps + 3)
#define MN_vfmaddsubps 0x3415
#define MN_vaddsubps 0x3421
#define MN_hsubps (MN_vhsubps + 1)
#define MN_vhsubps 0x342b
#define MN_vfmsubps 0x3433
#define MN_vfnmsubps 0x343c
#define MN_vsubps 0x3446
#define MN_vgatherpf0dps 0x344d
#define MN_vscatterpf0dps 0x345b
#define MN_vgatherpf1dps 0x346a
#define MN_vscatterpf1dps 0x3478
#define MN_addps (MN_vfmsubaddps + 6)
#define MN_vfmsubaddps 0x3487
#define MN_haddps (MN_vhaddps + 1)
#define MN_vhaddps 0x3493
#define MN_v4fmaddps 0x349b
#define MN_vfmaddps 0x34a5
#define MN_v4fnmaddps 0x34ae
#define MN_vfnmaddps 0x34b9
#define MN_vaddps 0x34c3
#define MN_andps (MN_vexpandps + 4)
#define MN_vexpandps 0x34ca
#define MN_vandps 0x34d4
#define MN_blendps (MN_vblendps + 1)
#define MN_vblendps 0x34db
#define MN_roundps (MN_vroundps + 1)
#define MN_vroundps 0x34e4
#define MN_vgatherdps 0x34ed
#define MN_vscatterdps 0x34f8
#define MN_cmpunordps (MN_vcmpunordps + 1)
#define MN_vcmpunordps 0x3504
#define MN_cmpordps (MN_vcmpordps + 1)
#define MN_vcmpordps 0x3510
#define MN_vreduceps 0x351a
#define MN_vrangeps 0x3524
#define MN_vcmpngeps 0x352d
#define MN_vcmpgeps 0x3537
#define MN_vrndscaleps 0x3540
#define MN_cmpnleps (MN_vcmpnleps + 1)
#define MN_vcmpnleps 0x354c
#define MN_cmpleps (MN_vcmpleps + 1)
#define MN_vcmpleps 0x3556
#define MN_vcmpfalseps 0x355f
#define MN_vcmptrueps 0x356b
#define MN_vscalefps 0x3576
#define MN_shufps (MN_vshufps + 1)
#define MN_vshufps 0x3580
#define MN_unpckhps (MN_vunpckhps + 1)
#define MN_vunpckhps 0x3588
#define MN_movlhps (MN_vmovlhps + 1)
#define MN_vmovlhps 0x3592
#define MN_movhps (MN_vmovhps + 1)
#define MN_vmovhps 0x359b
#define MN_movmskps (MN_vmovmskps + 1)
#define MN_vmovmskps 0x35a3
#define MN_movhlps (MN_vmovhlps + 1)
#define MN_vmovhlps 0x35ad
#define MN_vpermilps 0x35b6
#define MN_unpcklps (MN_vunpcklps + 1)
#define MN_vunpcklps 0x35c0
#define MN_mulps (MN_vmulps + 1)
#define MN_vmulps 0x35ca
#define MN_movlps (MN_vmovlps + 1)
#define MN_vmovlps 0x35d1
#define MN_cmps 0x35d9
#define MN_vblendmps 0x35de
#define MN_vfixupimmps 0x35e8
#define MN_vpermps 0x35f4
#define MN_andnps (MN_vandnps + 1)
#define MN_vandnps 0x35fc
#define MN_minps (MN_vminps + 1)
#define MN_vminps 0x3604
#define MN_seamops 0x360b
#define MN_rcpps (MN_vrcpps + 1)
#define MN_vrcpps 0x3613
#define MN_dpps (MN_vdpps + 1)
#define MN_vdpps 0x361a
#define MN_cmpps (MN_vcmpps + 1)
#define MN_vcmpps 0x3620
#define MN_vgetexpps 0x3627
#define MN_vgatherpf0qps 0x3631
#define MN_vscatterpf0qps 0x363f
#define MN_vgatherpf1qps 0x364e
#define MN_vscatterpf1qps 0x365c
#define MN_vcmpunord_qps 0x366b
#define MN_vcmpord_qps 0x3679
#define MN_cmpneqps (MN_vcmpneqps + 1)
#define MN_vcmpneqps 0x3685
#define MN_cmpeqps (MN_vcmpeqps + 1)
#define MN_vcmpeqps 0x368f
#define MN_vcmpge_oqps 0x3698
#define MN_vcmple_oqps 0x36a4
#define MN_vcmpfalse_oqps 0x36b0
#define MN_vcmpneq_oqps 0x36bf
#define MN_vcmpeq_oqps 0x36cc
#define MN_vcmpgt_oqps 0x36d8
#define MN_vcmplt_oqps 0x36e4
#define MN_vgatherqps 0x36f0
#define MN_vscatterqps 0x36fb
#define MN_vcmpnge_uqps 0x3707
#define MN_vcmpnle_uqps 0x3714
#define MN_vcmptrue_uqps 0x3721
#define MN_vcmpneq_uqps 0x372f
#define MN_vcmpeq_uqps 0x373c
#define MN_vcmpngt_uqps 0x3748
#define MN_vcmpnlt_uqps 0x3755
#define MN_orps (MN_vorps + 1)
#define MN_vorps 0x3762
#define MN_xorps (MN_vxorps + 1)
#define MN_vxorps 0x3768
#define MN_vcmpunord_sps 0x376f
#define MN_vcmpord_sps 0x377d
#define MN_vcmpge_osps 0x3789
#define MN_vcmple_osps 0x3795
#define MN_vcmpfalse_osps 0x37a1
#define MN_vcmpneq_osps 0x37b0
#define MN_vcmpeq_osps 0x37bd
#define MN_vcmpgt_osps 0x37c9
#define MN_vcmplt_osps 0x37d5
#define MN_vfpclassps 0x37e1
#define MN_vcompressps 0x37ec
#define MN_vcmpnge_usps 0x37f8
#define MN_vcmpnle_usps 0x3805
#define MN_vcmptrue_usps 0x3812
#define MN_vcmpneq_usps 0x3820
#define MN_vcmpeq_usps 0x382d
#define MN_vcmpngt_usps 0x3839
#define MN_vcmpnlt_usps 0x3846
#define MN_extractps (MN_vextractps + 1)
#define MN_vextractps 0x3853
#define MN_vcmpngtps 0x385e
#define MN_vcmpgtps 0x3868
#define MN_cmpnltps (MN_vcmpnltps + 1)
#define MN_vcmpnltps 0x3871
#define MN_cmpltps (MN_vcmpltps + 1)
#define MN_vcmpltps 0x387b
#define MN_vgetmantps 0x3884
#define MN_movntps (MN_vmovntps + 1)
#define MN_vmovntps 0x388f
#define MN_insertps (MN_vinsertps + 1)
#define MN_vinsertps 0x3898
#define MN_sqrtps (MN_rsqrtps + 1)
#define MN_rsqrtps (MN_vrsqrtps + 1)
#define MN_vrsqrtps 0x38a2
#define MN_vsqrtps 0x38ab
#define MN_vtestps 0x38b3
#define MN_movups (MN_vmovups + 1)
#define MN_vmovups 0x38bb
#define MN_blendvps (MN_vblendvps + 1)
#define MN_vblendvps 0x38c3
#define MN_divps (MN_vdivps + 1)
#define MN_vdivps 0x38cd
#define MN_vmaskmovps 0x38d4
#define MN_maxps (MN_vmaxps + 1)
#define MN_vmaxps 0x38df
#define MN_vfrczps 0x38e6
#define MN_xrstors 0x38ee
#define MN_ss (MN_vfmsub231ss + 9)
#define MN_vfmsub231ss 0x38f6
#define MN_vfnmsub231ss 0x3902
#define MN_vfmadd231ss 0x390f
#define MN_vfnmadd231ss 0x391b
#define MN_vfmsub132ss 0x3928
#define MN_vfnmsub132ss 0x3934
#define MN_vfmadd132ss 0x3941
#define MN_vfnmadd132ss 0x394d
#define MN_cvtsd2ss (MN_vcvtsd2ss + 1)
#define MN_vcvtsd2ss 0x395a
#define MN_vcvtsh2ss 0x3964
#define MN_cvtsi2ss (MN_vcvtsi2ss + 1)
#define MN_vcvtsi2ss 0x396e
#define MN_vcvtusi2ss 0x3978
#define MN_vfmsub213ss 0x3983
#define MN_vfnmsub213ss 0x398f
#define MN_vfmadd213ss 0x399c
#define MN_vfnmadd213ss 0x39a8
#define MN_vrcp14ss 0x39b5
#define MN_vrsqrt14ss 0x39be
#define MN_vrcp28ss 0x39c9
#define MN_vrsqrt28ss 0x39d2
#define MN_subss (MN_vfmsubss + 3)
#define MN_vfmsubss 0x39dd
#define MN_vfnmsubss 0x39e6
#define MN_vsubss 0x39f0
#define MN_addss (MN_v4fmaddss + 4)
#define MN_v4fmaddss 0x39f7
#define MN_vfmaddss 0x3a01
#define MN_v4fnmaddss 0x3a0a
#define MN_vfnmaddss 0x3a15
#define MN_vaddss 0x3a1f
#define MN_roundss (MN_vroundss + 1)
#define MN_vroundss 0x3a26
#define MN_cmpunordss (MN_vcmpunordss + 1)
#define MN_vcmpunordss 0x3a2f
#define MN_cmpordss (MN_vcmpordss + 1)
#define MN_vcmpordss 0x3a3b
#define MN_vreducess 0x3a45
#define MN_vrangess 0x3a4f
#define MN_vcmpngess 0x3a58
#define MN_vcmpgess 0x3a62
#define MN_vrndscaless 0x3a6b
#define MN_cmpnless (MN_vcmpnless + 1)
#define MN_vcmpnless 0x3a77
#define MN_cmpless (MN_vcmpless + 1)
#define MN_vcmpless 0x3a81
#define MN_vcmpfalsess 0x3a8a
#define MN_vcmptruess 0x3a96
#define MN_vscalefss 0x3aa1
#define MN_comiss (MN_ucomiss + 1)
#define MN_ucomiss (MN_vucomiss + 1)
#define MN_vucomiss 0x3aab
#define MN_vcomiss 0x3ab4
#define MN_lss (MN_mulss + 2)
#define MN_mulss (MN_vmulss + 1)
#define MN_vmulss 0x3abc
#define MN_vfixupimmss 0x3ac3
#define MN_minss (MN_vminss + 1)
#define MN_vminss 0x3acf
#define MN_rcpss (MN_vrcpss + 1)
#define MN_vrcpss 0x3ad6
#define MN_cmpss (MN_vcmpss + 1)
#define MN_vcmpss 0x3add
#define MN_vgetexpss 0x3ae4
#define MN_vcmpunord_qss 0x3aee
#define MN_vcmpord_qss 0x3afc
#define MN_cmpneqss (MN_vcmpneqss + 1)
#define MN_vcmpneqss 0x3b08
#define MN_cmpeqss (MN_vcmpeqss + 1)
#define MN_vcmpeqss 0x3b12
#define MN_vcmpge_oqss 0x3b1b
#define MN_vcmple_oqss 0x3b27
#define MN_vcmpfalse_oqss 0x3b33
#define MN_vcmpneq_oqss 0x3b42
#define MN_vcmpeq_oqss 0x3b4f
#define MN_vcmpgt_oqss 0x3b5b
#define MN_vcmplt_oqss 0x3b67
#define MN_vcmpnge_uqss 0x3b73
#define MN_vcmpnle_uqss 0x3b80
#define MN_vcmptrue_uqss 0x3b8d
#define MN_vcmpneq_uqss 0x3b9b
#define MN_vcmpeq_uqss 0x3ba8
#define MN_vcmpngt_uqss 0x3bb4
#define MN_vcmpnlt_uqss 0x3bc1
#define MN_vcmpunord_sss 0x3bce
#define MN_vcmpord_sss 0x3bdc
#define MN_vcmpge_osss 0x3be8
#define MN_vcmple_osss 0x3bf4
#define MN_vcmpfalse_osss 0x3c00
#define MN_vcmpneq_osss 0x3c0f
#define MN_vcmpeq_osss 0x3c1c
#define MN_vcmpgt_osss 0x3c28
#define MN_vcmplt_osss 0x3c34
#define MN_vfpclassss 0x3c40
#define MN_vcmpnge_usss 0x3c4b
#define MN_vcmpnle_usss 0x3c58
#define MN_vcmptrue_usss 0x3c65
#define MN_vcmpneq_usss 0x3c73
#define MN_vcmpeq_usss 0x3c80
#define MN_vcmpngt_usss 0x3c8c
#define MN_vcmpnlt_usss 0x3c99
#define MN_vcmpngtss 0x3ca6
#define MN_vcmpgtss 0x3cb0
#define MN_cmpnltss (MN_vcmpnltss + 1)
#define MN_vcmpnltss 0x3cb9
#define MN_cmpltss (MN_vcmpltss + 1)
#define MN_vcmpltss 0x3cc3
#define MN_vgetmantss 0x3ccc
#define MN_movntss 0x3cd7
#define MN_sqrtss (MN_rsqrtss + 1)
#define MN_rsqrtss (MN_vrsqrtss + 1)
#define MN_vrsqrtss 0x3cdf
#define MN_vsqrtss 0x3ce8
#define MN_vbroadcastss 0x3cf0
#define MN_divss (MN_vdivss + 1)
#define MN_vdivss 0x3cfd
#define MN_movss (MN_vmovss + 1)
#define MN_vmovss 0x3d04
#define MN_maxss (MN_vmaxss + 1)
#define MN_vmaxss 0x3d0b
#define MN_vfrczss 0x3d12
#define MN_bts 0x3d1a
#define MN_erets 0x3d1e
#define MN_sets 0x3d24
#define MN_clts 0x3d29
#define MN_outs 0x3d2e
#define MN_movs (MN_cmovs + 1)
#define MN_cmovs 0x3d33
#define MN_fldl2t 0x3d39
#define MN_xlat 0x3d40
#define MN_bt 0x3d45
#define MN_fxtract 0x3d48
#define MN_lgdt 0x3d50
#define MN_sgdt 0x3d55
#define MN_lidt 0x3d5a
#define MN_sidt 0x3d5f
#define MN_fldt 0x3d64
#define MN_lldt 0x3d69
#define MN_sldt 0x3d6e
#define MN_ret (MN_iret + 1)
#define MN_iret (MN_uiret + 1)
#define MN_uiret 0x3d73
#define MN_lret 0x3d79
#define MN_seamret 0x3d7e
#define MN_sysret 0x3d86
#define MN_hreset 0x3d8d
#define MN_pfcmpgt 0x3d94
#define MN_ht 0x3d9c
#define MN_wait (MN_fwait + 1)
#define MN_fwait 0x3d9f
#define MN_mwait (MN_umwait + 1)
#define MN_umwait 0x3da5
#define MN_mcommit 0x3dac
#define MN_finit 0x3db4
#define MN_skinit 0x3dba
#define MN_fninit 0x3dc1
#define MN_vmgexit 0x3dc8
#define MN_sysexit 0x3dd0
#define MN_hlt 0x3dd8
#define MN_popcnt 0x3ddc
#define MN_lzcnt 0x3de3
#define MN_tzcnt 0x3de9
#define MN_hnt 0x3def
#define MN_int (MN_frndint + 4)
#define MN_frndint 0x3df3
#define MN_not 0x3dfb
#define MN_invept 0x3dff
#define MN_xsaveopt 0x3e06
#define MN_clflushopt 0x3e0f
#define MN_fstpt 0x3e1a
#define MN_xabort 0x3e20
#define MN_fsqrt 0x3e27
#define MN_pfrsqrt 0x3e2d
#define MN_aesdeclast (MN_vaesdeclast + 1)
#define MN_vaesdeclast 0x3e35
#define MN_aesenclast (MN_vaesenclast + 1)
#define MN_vaesenclast 0x3e41
#define MN_test (MN_ptest + 1)
#define MN_ptest (MN_vptest + 1)
#define MN_vptest 0x3e4d
#define MN_xtest 0x3e54
#define MN_fst 0x3e5a
#define MN_fist 0x3e5e
#define MN_rdmsrlist 0x3e63
#define MN_wrmsrlist 0x3e6d
#define MN_aeskeygenassist (MN_vaeskeygenassist + 1)
#define MN_vaeskeygenassist 0x3e77
#define MN_vmptrst 0x3e88
#define MN_ftst 0x3e90
#define MN_rmpadjust 0x3e95
#define MN_out 0x3e9f
#define MN_pext 0x3ea3
#define MN_bndcu 0x3ea8
#define MN_enclu 0x3eae
#define MN_fcmovnu 0x3eb4
#define MN_lddqu (MN_vlddqu + 1)
#define MN_vlddqu 0x3ebc
#define MN_movdqu (MN_maskmovdqu + 4)
#define MN_maskmovdqu (MN_vmaskmovdqu + 1)
#define MN_vmaskmovdqu 0x3ec3
#define MN_vmovdqu 0x3ecf
#define MN_rdpkru 0x3ed7
#define MN_wrpkru 0x3ede
#define MN_rdpru 0x3ee5
#define MN_eretu 0x3eeb
#define MN_fcmovu 0x3ef1
#define MN_xgetbv 0x3ef8
#define MN_xsetbv 0x3eff
#define MN_div (MN_fdiv + 1)
#define MN_fdiv 0x3f06
#define MN_idiv (MN_fidiv + 1)
#define MN_fidiv 0x3f0b
#define MN_enclv 0x3f11
#define MN_fldenv 0x3f17
#define MN_fstenv 0x3f1e
#define MN_fnstenv 0x3f25
#define MN_mov (MN_vpcmov + 3)
#define MN_vpcmov 0x3f2d
#define MN_bndmov 0x3f34
#define MN_smov 0x3f3b
#define MN_rex_w 0x3f40
#define MN_vcvttph2w 0x3f46
#define MN_vcvtph2w 0x3f50
#define MN_vpermi2w 0x3f59
#define MN_vpmovm2w 0x3f62
#define MN_vpermt2w 0x3f6b
#define MN_vpshaw 0x3f74
#define MN_psraw (MN_vpsraw + 1)
#define MN_vpsraw 0x3f7b
#define MN_vphsubbw 0x3f82
#define MN_cbw 0x3f8b
#define MN_psadbw (MN_vdbpsadbw + 3)
#define MN_vdbpsadbw 0x3f8f
#define MN_mpsadbw (MN_vmpsadbw + 1)
#define MN_vmpsadbw 0x3f99
#define MN_vpsadbw 0x3fa2
#define MN_vphaddbw 0x3faa
#define MN_punpckhbw (MN_vpunpckhbw + 1)
#define MN_vpunpckhbw 0x3fb3
#define MN_kunpckbw 0x3fbe
#define MN_punpcklbw (MN_vpunpcklbw + 1)
#define MN_vpunpcklbw 0x3fc7
#define MN_vphaddubw 0x3fd2
#define MN_phsubw (MN_vphsubw + 1)
#define MN_vphsubw 0x3fdc
#define MN_psubw (MN_vpsubw + 1)
#define MN_vpsubw 0x3fe4
#define MN_pmovsxbw (MN_vpmovsxbw + 1)
#define MN_vpmovsxbw 0x3feb
#define MN_pmovzxbw (MN_vpmovzxbw + 1)
#define MN_vpmovzxbw 0x3ff5
#define MN_fldcw 0x3fff
#define MN_fstcw 0x4005
#define MN_fnstcw 0x400b
#define MN_phaddw (MN_vphaddw + 1)
#define MN_vphaddw 0x4012
#define MN_kaddw 0x401a
#define MN_paddw (MN_vpaddw + 1)
#define MN_vpaddw 0x4020
#define MN_vpshldw 0x4027
#define MN_kandw 0x402f
#define MN_vpexpandw 0x4035
#define MN_pblendw (MN_vpblendw + 1)
#define MN_vpblendw 0x403f
#define MN_vpshrdw 0x4048
#define MN_packssdw (MN_vpackssdw + 1)
#define MN_vpackssdw 0x4050
#define MN_packusdw (MN_vpackusdw + 1)
#define MN_vpackusdw 0x405a
#define MN_vpmovusdw 0x4064
#define MN_vpmovsdw 0x406e
#define MN_vpmovdw 0x4077
#define MN_vpcomgew 0x407f
#define MN_vpcomlew 0x4088
#define MN_vpcmpnlew 0x4091
#define MN_vpcmplew 0x409b
#define MN_vpcomfalsew 0x40a4
#define MN_vpcomtruew 0x40b0
#define MN_pi2fw 0x40bb
#define MN_pshufw 0x40c1
#define MN_pavgw (MN_vpavgw + 1)
#define MN_vpavgw 0x40c8
#define MN_prefetchw 0x40cf
#define MN_pshufhw (MN_vpshufhw + 1)
#define MN_vpshufhw 0x40d9
#define MN_pmulhw (MN_vpmulhw + 1)
#define MN_vpmulhw 0x40e2
#define MN_pf2iw 0x40ea
#define MN_pshuflw (MN_vpshuflw + 1)
#define MN_vpshuflw 0x40f0
#define MN_vpshlw 0x40f9
#define MN_psllw (MN_vpsllw + 1)
#define MN_vpsllw 0x4100
#define MN_pmullw (MN_vpmullw + 1)
#define MN_vpmullw 0x4107
#define MN_psrlw (MN_vpsrlw + 1)
#define MN_vpsrlw 0x410f
#define MN_kshiftlw 0x4116
#define MN_vpblendmw 0x411f
#define MN_vptestnmw 0x4129
#define MN_vpcomw 0x4133
#define MN_vpermw 0x413a
#define MN_vptestmw 0x4141
#define MN_kandnw 0x414a
#define MN_psignw (MN_vpsignw + 1)
#define MN_vpsignw 0x4151
#define MN_vpcmpw 0x4159
#define MN_vpcomeqw 0x4160
#define MN_vpcomneqw 0x4169
#define MN_vpcmpneqw 0x4173
#define MN_pcmpeqw (MN_vpcmpeqw + 1)
#define MN_vpcmpeqw 0x417d
#define MN_vpmovusqw 0x4186
#define MN_vpmovsqw 0x4190
#define MN_vpmovqw 0x4199
#define MN_verw 0x41a1
#define MN_pmulhrw 0x41a6
#define MN_korw 0x41ae
#define MN_kxnorw 0x41b3
#define MN_kxorw 0x41ba
#define MN_pinsrw (MN_vpinsrw + 1)
#define MN_vpinsrw 0x41c0
#define MN_kshiftrw 0x41c8
#define MN_pextrw (MN_vpextrw + 1)
#define MN_vpextrw 0x41d1
#define MN_pabsw (MN_vpabsw + 1)
#define MN_vpabsw 0x41d9
#define MN_pmaddubsw (MN_vpmaddubsw + 1)
#define MN_vpmaddubsw 0x41e0
#define MN_phsubsw (MN_vphsubsw + 1)
#define MN_vphsubsw 0x41eb
#define MN_psubsw (MN_vpsubsw + 1)
#define MN_vpsubsw 0x41f4
#define MN_phaddsw (MN_vphaddsw + 1)
#define MN_vphaddsw 0x41fc
#define MN_paddsw (MN_vpaddsw + 1)
#define MN_vpaddsw 0x4205
#define MN_lmsw 0x420d
#define MN_smsw 0x4212
#define MN_pminsw (MN_vpminsw + 1)
#define MN_vpminsw 0x4217
#define MN_pmulhrsw (MN_vpmulhrsw + 1)
#define MN_vpmulhrsw 0x421f
#define MN_vpcompressw 0x4229
#define MN_fstsw 0x4235
#define MN_fnstsw 0x423b
#define MN_psubusw (MN_vpsubusw + 1)
#define MN_vpsubusw 0x4242
#define MN_paddusw (MN_vpaddusw + 1)
#define MN_vpaddusw 0x424b
#define MN_movsw 0x4254
#define MN_pmaxsw (MN_vpmaxsw + 1)
#define MN_vpmaxsw 0x425a
#define MN_cbtw 0x4262
#define MN_vpcomgtw 0x4267
#define MN_pcmpgtw (MN_vpcmpgtw + 1)
#define MN_vpcmpgtw 0x4270
#define MN_vpcomltw 0x4279
#define MN_vpcmpnltw 0x4282
#define MN_vpcmpltw 0x428c
#define MN_vpopcntw 0x4295
#define MN_knotw 0x429e
#define MN_vprotw 0x42a4
#define MN_vpbroadcastw 0x42ab
#define MN_ktestw 0x42b8
#define MN_kortestw 0x42bf
#define MN_vcvttph2uw 0x42c8
#define MN_vcvtph2uw 0x42d3
#define MN_vpcomgeuw 0x42dd
#define MN_vpcomleuw 0x42e7
#define MN_vpcmpnleuw 0x42f1
#define MN_vpcmpleuw 0x42fc
#define MN_vpcomfalseuw 0x4306
#define MN_vpcomtrueuw 0x4313
#define MN_pmulhuw (MN_vpmulhuw + 1)
#define MN_vpmulhuw 0x431f
#define MN_vpcomuw 0x4328
#define MN_pminuw (MN_vpminuw + 1)
#define MN_vpminuw 0x4330
#define MN_vpcmpuw 0x4338
#define MN_vpcomequw 0x4340
#define MN_vpcomnequw 0x434a
#define MN_vpcmpnequw 0x4355
#define MN_vpcmpequw 0x4360
#define MN_phminposuw (MN_vphminposuw + 1)
#define MN_vphminposuw 0x436a
#define MN_vpcomgtuw 0x4376
#define MN_vpcomltuw 0x4380
#define MN_vpcmpnltuw 0x438a
#define MN_vpcmpltuw 0x4395
#define MN_pmaxuw (MN_vpmaxuw + 1)
#define MN_vpmaxuw 0x439f
#define MN_vpsravw 0x43a7
#define MN_vpshldvw 0x43af
#define MN_vpshrdvw 0x43b8
#define MN_vpsllvw 0x43c1
#define MN_vpsrlvw 0x43c9
#define MN_kmovw 0x43d1
#define MN_vmovw 0x43d7
#define MN_vpmacsww 0x43dd
#define MN_vpmacssww 0x43e6
#define MN_movzw 0x43f0
#define MN_rex_x 0x43f6
#define MN_fyl2x 0x43fc
#define MN_rex64x 0x4402
#define MN_vcvtneps2bf16x 0x4409
#define MN_pfmax 0x4418
#define MN_adcx 0x441e
#define MN_bndldx 0x4423
#define MN_vfpclasspdx 0x442a
#define MN_fclex 0x4436
#define MN_fnclex 0x443c
#define MN_rex 0x4443
#define MN_vcvtpd2phx 0x4447
#define MN_vcvtdq2phx 0x4452
#define MN_vcvtudq2phx 0x445d
#define MN_vcvtqq2phx 0x4469
#define MN_vcvtuqq2phx 0x4474
#define MN_vcvtps2phx 0x4480
#define MN_vfpclassphx 0x448b
#define MN_shlx 0x4497
#define MN_mulx 0x449c
#define MN_adox 0x44a1
#define MN_vcvttpd2dqx 0x44a6
#define MN_vcvtpd2dqx 0x44b2
#define MN_vcvttpd2udqx 0x44bd
#define MN_vcvtpd2udqx 0x44ca
#define MN_rex_rx 0x44d6
#define MN_sarx 0x44dd
#define MN_shrx 0x44e2
#define MN_rorx 0x44e7
#define MN_monitorx 0x44ec
#define MN_rex_wrx 0x44f5
#define MN_vcvtpd2psx 0x44fd
#define MN_vcvtph2psx 0x4508
#define MN_vcvtqq2psx 0x4513
#define MN_vcvtuqq2psx 0x451e
#define MN_vfpclasspsx 0x452a
#define MN_movsx 0x4536
#define MN_mwaitx 0x453c
#define MN_bndstx 0x4543
#define MN_rex_wx 0x454a
#define MN_rexx 0x4551
#define MN_vcvtps2phxx 0x4556
#define MN_movzx 0x4562
#define MN_rex64y 0x4568
#define MN_vcvtneps2bf16y 0x456f
#define MN_vfpclasspdy 0x457e
#define MN_loadiwkey 0x458a
#define MN_vcvtpd2phy 0x4594
#define MN_vcvtdq2phy 0x459f
#define MN_vcvtudq2phy 0x45aa
#define MN_vcvtqq2phy 0x45b6
#define MN_vcvtuqq2phy 0x45c1
#define MN_vfpclassphy 0x45cd
#define MN_vcvttpd2dqy 0x45d9
#define MN_vcvtpd2dqy 0x45e5
#define MN_vcvttpd2udqy 0x45f0
#define MN_vcvtpd2udqy 0x45fd
#define MN_rmpquery 0x4609
#define MN_clrssbsy 0x4612
#define MN_setssbsy 0x461b
#define MN_vcvtpd2psy 0x4624
#define MN_vcvtqq2psy 0x462f
#define MN_vcvtuqq2psy 0x463a
#define MN_vfpclasspsy 0x4646
#define MN_rex64xy 0x4652
#define MN_rexy 0x465a
#define MN_vcvtps2phxy 0x465f
#define MN_rexxy 0x466b
#define MN_rex64z 0x4671
#define MN_fldz 0x4678
#define MN_vfpclasspdz 0x467d
#define MN_vcvtpd2phz 0x4689
#define MN_vcvtqq2phz 0x4694
#define MN_vcvtuqq2phz 0x469f
#define MN_vfpclassphz 0x46ab
#define MN_jz 0x46b7
#define MN_jnz 0x46ba
#define MN_repnz 0x46be
#define MN_loopnz 0x46c4
#define MN_setnz 0x46cb
#define MN_cmovnz 0x46d1
#define MN_repz 0x46d8
#define MN_loopz 0x46dd
#define MN_vfpclasspsz 0x46e3
#define MN_setz 0x46ef
#define MN_cmovz 0x46f4
#define MN_rex64xz 0x46fa
#define MN_jecxz 0x4702
#define MN_jcxz 0x4708
#define MN_jrcxz 0x470d
#define MN_rexz 0x4713
#define MN_rexxz 0x4718
#define MN_rex64yz 0x471e
#define MN_rex64xyz 0x4726
#define MN_rexyz 0x472f
#define MN_rexxyz 0x4735
#define MN__disp32_ 0x473c
#define MN__rex2_ 0x4745
#define MN__vex2_ 0x474c
#define MN__vex3_ 0x4753
#define MN__disp16_ 0x475a
#define MN__disp8_ 0x4763
#define MN__load_ 0x476b
#define MN__store_ 0x4772
#define MN__nooptimize_ 0x477a
#define MN__rex_ 0x4787
#define MN__evex_ 0x478d
#define MN__vex_ 0x4794
#define MN__insn 0x479a
