# Copyright 2023-2024 Free Software Foundation, Inc.

# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.

# This file is a dejagnu "board file" and is used to run the testsuite
# with contrib/cc-with-tweaks.sh -c.
#
# Example usage:
# bash$ cd $objdir
# bash$ make check-gdb \
#   RUNTESTFLAGS='--target_board=cc-with-index-cache'
#

# Choose location of index-cache directory.
setenv INDEX_CACHE_DIR [pwd]/cc-with-index-cache

# Start with empty index-cache directory.
file delete -force $env(INDEX_CACHE_DIR)
file mkdir $env(INDEX_CACHE_DIR)

# Make sure index-cache entries are generated for each executable.
set CC_WITH_TWEAKS_FLAGS "-c"
load_board_description "cc-with-tweaks"

# Make sure gdb knowns how to find the index-cache.
append GDBFLAGS " -iex \"set index-cache directory $env(INDEX_CACHE_DIR)\""

# Make sure gdb uses the index-cache.
append GDBFLAGS " -iex \"set index-cache enabled on\""
