# Copyright 2014-2024 Free Software Foundation, Inc.

# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.

standard_testfile

require {!is_remote host}

set targetdir "${binfile}.dir"
set sourcescript "${srcdir}/${subdir}/${testfile}-script"
set targetscriptdir "${targetdir}/[file dirname ${binfile}]"
set targetscript "${targetscriptdir}/${testfile}-gdb.gdb"

remote_exec host "rm -rf ${targetdir}"

if { [prepare_for_testing "failed to prepare" ${testfile} ${srcfile}] } {
    return -1
}

remote_exec host "mkdir -p ${targetscriptdir}"
remote_exec host "cp ${sourcescript} ${targetscript}"

gdb_test_no_output "set auto-load scripts-directory ${targetdir}" "set auto-load scripts-directory"
gdb_test_no_output "set auto-load safe-path ${targetscript}" "set auto-load safe-path"

gdb_load ${binfile}

gdb_test {print $script_loaded} " = 42"
