# Copyright 2020-2024 Free Software Foundation, Inc.

# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.  */

standard_testfile decl-before-def-decl.c decl-before-def-def.c
set sources [list $srcfile $srcfile2]

if {[prepare_for_testing "failed to prepare" $testfile $sources]} {
    return -1
}

# This is required due to PR25764.
gdb_test "maint expand-symtabs"

gdb_test "p a" { = \{1, 2\}} "no running process: p a"

if {![runto_main]} {
    return 0
}

gdb_test "p a" { = \{1, 2\}} "running process: p a"
