# Copyright 2007-2024 Free Software Foundation, Inc.
#
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.
#
# This file is part of the gdb testsuite.

# It's possible to have a program that contains two compilation units
# for the same source file name, that have code at different lines.
# For example, in this test, we compile expand-psymtabs.c twice with
# different preprocessor symbols #defined; the first .o only has
# 'main' at some earlier source lines, while the second .o only has
# 'foo' at later source lines.  So when setting breakpoints by line
# number, which full symtab we need depends on the line number in
# question.
#
# This test is meant to verify that, even with lazy partial symtab
# reading in effect, GDB can set breakpoints by line number
# successfully in either compilation unit.  

standard_testfile

# We intentionally compile the source file in twice.
if {[prepare_for_testing_full "failed to prepare" \
	 [list $testfile debug $srcfile {debug additional_flags=-DFIRST} \
	      $srcfile debug]]} {
    return -1
}

set foo_bp [gdb_get_line_number "Break here"]
gdb_test "break $foo_bp" "Breakpoint.*" "expand psymtabs"

