# Copyright 2013-2024 Free Software Foundation, Inc.

# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.

# This testcase exercises bug 15695.
# Trying to print foo->bar if foo is a pointer to a typedef of a pointer
# to a function will put gdb into an infinite loop.

if { [prepare_for_testing "failed to prepare" "func-ptr" {func-ptr.c} {debug}] } {
    return -1
}

if ![runto_main] {
    return 0
}

# This would put gdb into an infinite loop.
gdb_test "print pbar->baz" "Attempt to extract .*"
