# Copyright 2020-2024 Free Software Foundation, Inc.

# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.  */

standard_testfile

if {[prepare_for_testing "failed to prepare" $testfile $srcfile debug]} {
    return -1
}

if {![runto_main]} {
    return 0
}

set supported 0
gdb_test_multiple "l main:L1" "" {
    -wrap -re "No label \"L1\" defined in function \"main\"\." {
	unsupported $gdb_test_name
    }
    -wrap -re "L1:\r\n.*" {
	pass $gdb_test_name
	set supported 1
    }
}

if { ! $supported } {
    return -1
}

gdb_test "break main:L1" "Location main:L1 not available"
