# Copyright (C) 2012-2024 Free Software Foundation, Inc.
#
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.

standard_testfile .c

if { [prepare_for_testing "failed to prepare" ${testfile} ${srcfile}] } {
    return -1
}

if ![runto_main] {
    return -1
}

gdb_test "break $srcfile:[gdb_get_line_number BREAK $srcfile] if n == 3" \
         "Breakpoint $decimal at $hex: file .*recpar\\.c, line $decimal\\."

gdb_test "continue" \
         "Breakpoint .* foo \\(n=3\\) at .*$srcfile:$decimal.*"

gdb_test "backtrace" \
         "#0 +foo \\(n=3\\).*\r\n#1.* foo \\(n=4\\).*\r\n#2.* foo \\(n=5\\).*#3.* main \\(\\).*"

gdb_test "frame 2" \
         "#2 .* foo \\(n=5\\) .*"

# In the currently selected frame, n=5, and thus foo::val should be 5
# as well.
gdb_test "print foo::val" \
         " = 5"
