# Copyright 2023-2024 Free Software Foundation, Inc.

# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.

# Test that GDB displays the correct error message when hardware watchpoints
# are not supported or explicitly disabled.  Test also that GDB terminates
# successfully after several attempts to insert a hardware watchpoint.

standard_testfile

if {[prepare_for_testing "failed to prepare" ${testfile} ${srcfile}]} {
    return -1
}

gdb_test_no_output "set can-use-hw-watchpoints 0"

if {![runto_main]} {
    return -1
}

gdb_test "awatch a" \
    "Can't set read/access watchpoint when hardware watchpoints are disabled." \
    "unsuccessful attempt to create an access watchpoint"
gdb_test "rwatch b" \
    "Can't set read/access watchpoint when hardware watchpoints are disabled." \
    "unsuccessful attempt to create a read watchpoint"

# The program continues until termination.
gdb_continue_to_end
