# Copyright 2008-2024 Free Software Foundation, Inc.
#
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.


standard_testfile .c

if  { [gdb_compile "${srcdir}/${subdir}/${srcfile}" "${binfile}" executable [concat debug additional_flags=-fstack-check nowarnings]] != "" } {
     untested "failed to compile"
     return -1
}

clean_restart ${binfile}

if {![runto_main]} {
    return 0
}


# Test that the debugger is able to unwind to "main" at the next breakpoint
# hit. The frame number of "main" should be passed into MAIN_FRAME_NUMBER."
proc backtrace_test {name main_frame_number} {
    with_test_prefix $name {
	gdb_continue_to_breakpoint "test location"
	gdb_test "bt" "#${main_frame_number}.*in main ().*"
    }
}

gdb_breakpoint [gdb_get_line_number "set breakpoint here"]
backtrace_test "small frame" "1"
backtrace_test "medium frame" "2"
backtrace_test "big frame" "2"
