# Copyright (C) 2010-2024 Free Software Foundation, Inc.

# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.

standard_testfile

if { [prepare_for_testing "failed to prepare" ${testfile} $srcfile] } {
    return -1
}

if ![runto_main] {
    return -1
}

gdb_test "step" " in-func .*"
gdb_test "up" " call-func .*"
gdb_test_no_output {set $b=$pc}

if ![runto_main] {
    return -1
}

gdb_breakpoint {*$b if cond ()}

set test {print $bpnum}
gdb_test_multiple $test $test {
    -re " = (\[0-9\]+)\r\n$gdb_prompt $" {
	set caller_bp $expect_out(1,string)
	pass $test
    }
}

# Debug only:
gdb_test "disass/m" ".*"
gdb_test "info breakpoints" ".*"

gdb_test "next" "Breakpoint $caller_bp, .* call-func .*"

# `cond-hit' is now hit twice; but it may not be in the future.  It is
# currently not a bug so it is not KFAILed.
gdb_test "p cond_hit" { = [12]}
