# Copyright 1998-2024 Free Software Foundation, Inc.

# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.

standard_testfile .c

if { [prepare_for_testing "failed to prepare" $binfile $srcfile {debug}] } {
    return -1
}

if {![runto_main]} {
    return 0
}

gdb_test "f" \
    ".*bkpt = 0.*" \
    "structs2 sanity check"

gdb_test "break param_reg" \
    "Breakpoint .* at .*" \
    "structs2 breakpoint set"

if [test_compiler_info gcc-3-*] {
  setup_xfail hppa*-* gcc/15860
}
gdb_test "continue" \
    ".*pr_char=120.*pr_uchar=130.*pr_short=32000.*pr_ushort=33000.*bkpt = 1.*" \
    "structs2 continue1"

if [test_compiler_info gcc-3-*] {
  setup_xfail hppa*-* gcc/15860
}
gdb_test "continue" \
    ".*pr_char=-120.*pr_uchar=130.*pr_short=-32000.*pr_ushort=33000.*bkpt = 1.*" \
    "structs2 continue2"
