# Copyright 2020-2024 Free Software Foundation, Inc.

# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.

# This serves as a template for writing new test cases.  Replace this with
# a description of what this test case tests.

standard_testfile

if { [prepare_for_testing "failed to prepare" \
	${testfile} ${srcfile}] } {
    return
}

if { ![runto_main] } {
    return
}

set lineno [gdb_get_line_number "next-line"]
gdb_test "advance $lineno" "next-line.*" "advance to next-line"
