# Copyright 2014-2024 Free Software Foundation, Inc.

# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.

standard_testfile .c vla-stub-define.c
if { [prepare_for_testing "failed to prepare for vla-stub.exp" \
      ${testfile} [list ${srcfile} ${srcfile2}]] } {
    return -1
}

gdb_test "p *local_struct.ptr" { = {dynamic_field = 0x0}}

gdb_test "whatis local_struct.here" "type = static_struct_t"
gdb_test "whatis *local_struct.ptr" "type = dynamic_struct_t"
