# Copyright (C) 2018-2024 Free Software Foundation, Inc.

# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.

# Contributed by Jozef Lawrynowicz (jozef.l@mittosystems.com)

# Test for PR gdb/20948
# Verify that invoking gdb with the --write argument works as expected

global GDBFLAGS
standard_testfile

if {[build_executable $testfile.exp $testfile \
	$srcfile [list debug nowarnings] ] == -1} {
    untested $testfile.exp
    return -1
}

set old_gdbflags $GDBFLAGS

# Expect a failure before --write has been added to the command line
set GDBFLAGS "$old_gdbflags $binfile"
clean_restart
test_print_reject "set {int}main = 0x4242" "Cannot access memory at address"

# Setting memory should now work correctly after adding --write
set GDBFLAGS "$old_gdbflags --write $binfile"
clean_restart
gdb_test_no_output "set {int}main = 0x4242"

# Check that memory write persists after quitting GDB
gdb_exit
gdb_start
gdb_test "x /x main" "<main>:.*4242"

set GDBFLAGS $old_gdbflags
