/*
 * This file contains the system call numbers.
 */

#define TARGET_LINUX_SYS_exit		  1
#define TARGET_LINUX_SYS_fork		  2
#define TARGET_LINUX_SYS_read		  3
#define TARGET_LINUX_SYS_write		  4
#define TARGET_LINUX_SYS_open		  5
#define TARGET_LINUX_SYS_close		  6
#define TARGET_LINUX_SYS_waitpid		  7
#define TARGET_LINUX_SYS_creat		  8
#define TARGET_LINUX_SYS_link		  9
#define TARGET_LINUX_SYS_unlink		 10
#define TARGET_LINUX_SYS_execve		 11
#define TARGET_LINUX_SYS_chdir		 12
#define TARGET_LINUX_SYS_time		 13
#define TARGET_LINUX_SYS_mknod		 14
#define TARGET_LINUX_SYS_chmod		 15
#define TARGET_LINUX_SYS_lchown		 16
#define TARGET_LINUX_SYS_break		 17
#define TARGET_LINUX_SYS_oldstat		 18
#define TARGET_LINUX_SYS_lseek		 19
#define TARGET_LINUX_SYS_getpid		 20
#define TARGET_LINUX_SYS_mount		 21
#define TARGET_LINUX_SYS_umount		 22
#define TARGET_LINUX_SYS_setuid		 23
#define TARGET_LINUX_SYS_getuid		 24
#define TARGET_LINUX_SYS_stime		 25
#define TARGET_LINUX_SYS_ptrace		 26
#define TARGET_LINUX_SYS_alarm		 27
#define TARGET_LINUX_SYS_oldfstat		 28
#define TARGET_LINUX_SYS_pause		 29
#define TARGET_LINUX_SYS_utime		 30
#define TARGET_LINUX_SYS_stty		 31
#define TARGET_LINUX_SYS_gtty		 32
#define TARGET_LINUX_SYS_access		 33
#define TARGET_LINUX_SYS_nice		 34
#define TARGET_LINUX_SYS_ftime		 35
#define TARGET_LINUX_SYS_sync		 36
#define TARGET_LINUX_SYS_kill		 37
#define TARGET_LINUX_SYS_rename		 38
#define TARGET_LINUX_SYS_mkdir		 39
#define TARGET_LINUX_SYS_rmdir		 40
#define TARGET_LINUX_SYS_dup		 41
#define TARGET_LINUX_SYS_pipe		 42
#define TARGET_LINUX_SYS_times		 43
#define TARGET_LINUX_SYS_prof		 44
#define TARGET_LINUX_SYS_brk		 45
#define TARGET_LINUX_SYS_setgid		 46
#define TARGET_LINUX_SYS_getgid		 47
#define TARGET_LINUX_SYS_signal		 48
#define TARGET_LINUX_SYS_geteuid		 49
#define TARGET_LINUX_SYS_getegid		 50
#define TARGET_LINUX_SYS_acct		 51
#define TARGET_LINUX_SYS_umount2		 52
#define TARGET_LINUX_SYS_lock		 53
#define TARGET_LINUX_SYS_ioctl		 54
#define TARGET_LINUX_SYS_fcntl		 55
#define TARGET_LINUX_SYS_mpx		 56
#define TARGET_LINUX_SYS_setpgid		 57
#define TARGET_LINUX_SYS_ulimit		 58
#define TARGET_LINUX_SYS_oldolduname	 59
#define TARGET_LINUX_SYS_umask		 60
#define TARGET_LINUX_SYS_chroot		 61
#define TARGET_LINUX_SYS_ustat		 62
#define TARGET_LINUX_SYS_dup2		 63
#define TARGET_LINUX_SYS_getppid		 64
#define TARGET_LINUX_SYS_getpgrp		 65
#define TARGET_LINUX_SYS_setsid		 66
#define TARGET_LINUX_SYS_sigaction		 67
#define TARGET_LINUX_SYS_sgetmask		 68
#define TARGET_LINUX_SYS_ssetmask		 69
#define TARGET_LINUX_SYS_setreuid		 70
#define TARGET_LINUX_SYS_setregid		 71
#define TARGET_LINUX_SYS_sigsuspend		 72
#define TARGET_LINUX_SYS_sigpending		 73
#define TARGET_LINUX_SYS_sethostname	 74
#define TARGET_LINUX_SYS_setrlimit		 75
#define TARGET_LINUX_SYS_getrlimit		 76
#define TARGET_LINUX_SYS_getrusage		 77
#define TARGET_LINUX_SYS_gettimeofday	 78
#define TARGET_LINUX_SYS_settimeofday	 79
#define TARGET_LINUX_SYS_getgroups		 80
#define TARGET_LINUX_SYS_setgroups		 81
#define TARGET_LINUX_SYS_select		 82
#define TARGET_LINUX_SYS_symlink		 83
#define TARGET_LINUX_SYS_oldlstat		 84
#define TARGET_LINUX_SYS_readlink		 85
#define TARGET_LINUX_SYS_uselib		 86
#define TARGET_LINUX_SYS_swapon		 87
#define TARGET_LINUX_SYS_reboot		 88
#define TARGET_LINUX_SYS_readdir		 89
#define TARGET_LINUX_SYS_mmap		 90
#define TARGET_LINUX_SYS_munmap		 91
#define TARGET_LINUX_SYS_truncate		 92
#define TARGET_LINUX_SYS_ftruncate		 93
#define TARGET_LINUX_SYS_fchmod		 94
#define TARGET_LINUX_SYS_fchown		 95
#define TARGET_LINUX_SYS_getpriority	 96
#define TARGET_LINUX_SYS_setpriority	 97
#define TARGET_LINUX_SYS_profil		 98
#define TARGET_LINUX_SYS_statfs		 99
#define TARGET_LINUX_SYS_fstatfs		100
#define TARGET_LINUX_SYS_ioperm		101
#define TARGET_LINUX_SYS_socketcall		102
#define TARGET_LINUX_SYS_syslog		103
#define TARGET_LINUX_SYS_setitimer		104
#define TARGET_LINUX_SYS_getitimer		105
#define TARGET_LINUX_SYS_stat		106
#define TARGET_LINUX_SYS_lstat		107
#define TARGET_LINUX_SYS_fstat		108
#define TARGET_LINUX_SYS_olduname		109
#define TARGET_LINUX_SYS_iopl		110
#define TARGET_LINUX_SYS_vhangup		111
#define TARGET_LINUX_SYS_idle		112
#define TARGET_LINUX_SYS_vm86old		113
#define TARGET_LINUX_SYS_wait4		114
#define TARGET_LINUX_SYS_swapoff		115
#define TARGET_LINUX_SYS_sysinfo		116
#define TARGET_LINUX_SYS_ipc		117
#define TARGET_LINUX_SYS_fsync		118
#define TARGET_LINUX_SYS_sigreturn		119
#define TARGET_LINUX_SYS_clone		120
#define TARGET_LINUX_SYS_setdomainname	121
#define TARGET_LINUX_SYS_uname		122
#define TARGET_LINUX_SYS_modify_ldt		123
#define TARGET_LINUX_SYS_adjtimex		124
#define TARGET_LINUX_SYS_mprotect		125
#define TARGET_LINUX_SYS_sigprocmask	126
#define TARGET_LINUX_SYS_create_module	127
#define TARGET_LINUX_SYS_init_module	128
#define TARGET_LINUX_SYS_delete_module	129
#define TARGET_LINUX_SYS_get_kernel_syms	130
#define TARGET_LINUX_SYS_quotactl		131
#define TARGET_LINUX_SYS_getpgid		132
#define TARGET_LINUX_SYS_fchdir		133
#define TARGET_LINUX_SYS_bdflush		134
#define TARGET_LINUX_SYS_sysfs		135
#define TARGET_LINUX_SYS_personality	136
#define TARGET_LINUX_SYS_afs_syscall	137 /* Syscall for Andrew File System */
#define TARGET_LINUX_SYS_setfsuid		138
#define TARGET_LINUX_SYS_setfsgid		139
#define TARGET_LINUX_SYS__llseek		140
#define TARGET_LINUX_SYS_getdents		141
#define TARGET_LINUX_SYS__newselect		142
#define TARGET_LINUX_SYS_flock		143
#define TARGET_LINUX_SYS_msync		144
#define TARGET_LINUX_SYS_readv		145
#define TARGET_LINUX_SYS_writev		146
#define TARGET_LINUX_SYS_getsid		147
#define TARGET_LINUX_SYS_fdatasync		148
#define TARGET_LINUX_SYS__sysctl		149
#define TARGET_LINUX_SYS_mlock		150
#define TARGET_LINUX_SYS_munlock		151
#define TARGET_LINUX_SYS_mlockall		152
#define TARGET_LINUX_SYS_munlockall		153
#define TARGET_LINUX_SYS_sched_setparam		154
#define TARGET_LINUX_SYS_sched_getparam		155
#define TARGET_LINUX_SYS_sched_setscheduler		156
#define TARGET_LINUX_SYS_sched_getscheduler		157
#define TARGET_LINUX_SYS_sched_yield		158
#define TARGET_LINUX_SYS_sched_get_priority_max	159
#define TARGET_LINUX_SYS_sched_get_priority_min	160
#define TARGET_LINUX_SYS_sched_rr_get_interval	161
#define TARGET_LINUX_SYS_nanosleep		162
#define TARGET_LINUX_SYS_mremap		163
#define TARGET_LINUX_SYS_setresuid		164
#define TARGET_LINUX_SYS_getresuid		165
#define TARGET_LINUX_SYS_vm86		166
#define TARGET_LINUX_SYS_query_module	167
#define TARGET_LINUX_SYS_poll		168
#define TARGET_LINUX_SYS_nfsservctl		169
#define TARGET_LINUX_SYS_setresgid		170
#define TARGET_LINUX_SYS_getresgid		171
#define TARGET_LINUX_SYS_prctl              172
#define TARGET_LINUX_SYS_rt_sigreturn	173
#define TARGET_LINUX_SYS_rt_sigaction	174
#define TARGET_LINUX_SYS_rt_sigprocmask	175
#define TARGET_LINUX_SYS_rt_sigpending	176
#define TARGET_LINUX_SYS_rt_sigtimedwait	177
#define TARGET_LINUX_SYS_rt_sigqueueinfo	178
#define TARGET_LINUX_SYS_rt_sigsuspend	179
#define TARGET_LINUX_SYS_pread		180
#define TARGET_LINUX_SYS_pwrite		181
#define TARGET_LINUX_SYS_chown		182
#define TARGET_LINUX_SYS_getcwd		183
#define TARGET_LINUX_SYS_capget		184
#define TARGET_LINUX_SYS_capset		185
#define TARGET_LINUX_SYS_sigaltstack	186
#define TARGET_LINUX_SYS_sendfile		187
#define TARGET_LINUX_SYS_getpmsg		188	/* some people actually want streams */
#define TARGET_LINUX_SYS_putpmsg		189	/* some people actually want streams */
#define TARGET_LINUX_SYS_vfork		190

#define TARGET_LINUX_SYS_pread64		180
#define TARGET_LINUX_SYS_pwrite64		181

#define TARGET_LINUX_SYS_ugetrlimit		191	/* SuS compliant getrlimit */
#define TARGET_LINUX_SYS_mmap2		192
#define TARGET_LINUX_SYS_truncate64		193
#define TARGET_LINUX_SYS_ftruncate64	194
#define TARGET_LINUX_SYS_stat64		195
#define TARGET_LINUX_SYS_lstat64		196
#define TARGET_LINUX_SYS_fstat64		197
#define TARGET_LINUX_SYS_lchown32		198
#define TARGET_LINUX_SYS_getuid32		199
#define TARGET_LINUX_SYS_getgid32		200
#define TARGET_LINUX_SYS_geteuid32		201
#define TARGET_LINUX_SYS_getegid32		202
#define TARGET_LINUX_SYS_setreuid32		203
#define TARGET_LINUX_SYS_setregid32		204
#define TARGET_LINUX_SYS_getgroups32	205
#define TARGET_LINUX_SYS_setgroups32	206
#define TARGET_LINUX_SYS_fchown32		207
#define TARGET_LINUX_SYS_setresuid32	208
#define TARGET_LINUX_SYS_getresuid32	209
#define TARGET_LINUX_SYS_setresgid32	210
#define TARGET_LINUX_SYS_getresgid32	211
#define TARGET_LINUX_SYS_chown32		212
#define TARGET_LINUX_SYS_setuid32		213
#define TARGET_LINUX_SYS_setgid32		214
#define TARGET_LINUX_SYS_setfsuid32		215
#define TARGET_LINUX_SYS_setfsgid32		216
#define TARGET_LINUX_SYS_pivot_root		217
#define TARGET_LINUX_SYS_mincore		218
#define TARGET_LINUX_SYS_madvise		219
#define TARGET_LINUX_SYS_madvise1		219	/* delete when C lib stub is removed */
#define TARGET_LINUX_SYS_getdents64		220
#define TARGET_LINUX_SYS_fcntl64		221
/* 223 is unused */
#define TARGET_LINUX_SYS_gettid		224
#define TARGET_LINUX_SYS_readahead		225
#define TARGET_LINUX_SYS_setxattr		226
#define TARGET_LINUX_SYS_lsetxattr		227
#define TARGET_LINUX_SYS_fsetxattr		228
#define TARGET_LINUX_SYS_getxattr		229
#define TARGET_LINUX_SYS_lgetxattr		230
#define TARGET_LINUX_SYS_fgetxattr		231
#define TARGET_LINUX_SYS_listxattr		232
#define TARGET_LINUX_SYS_llistxattr		233
#define TARGET_LINUX_SYS_flistxattr		234
#define TARGET_LINUX_SYS_removexattr	235
#define TARGET_LINUX_SYS_lremovexattr	236
#define TARGET_LINUX_SYS_fremovexattr	237
#define TARGET_LINUX_SYS_tkill		238
#define TARGET_LINUX_SYS_sendfile64		239
#define TARGET_LINUX_SYS_futex		240
#define TARGET_LINUX_SYS_sched_setaffinity	241
#define TARGET_LINUX_SYS_sched_getaffinity	242
#define TARGET_LINUX_SYS_set_thread_area	243
#define TARGET_LINUX_SYS_get_thread_area	244
#define TARGET_LINUX_SYS_io_setup		245
#define TARGET_LINUX_SYS_io_destroy		246
#define TARGET_LINUX_SYS_io_getevents	247
#define TARGET_LINUX_SYS_io_submit		248
#define TARGET_LINUX_SYS_io_cancel		249
#define TARGET_LINUX_SYS_fadvise64		250

#define TARGET_LINUX_SYS_exit_group		252
#define TARGET_LINUX_SYS_lookup_dcookie	253
#define TARGET_LINUX_SYS_epoll_create	254
#define TARGET_LINUX_SYS_epoll_ctl		255
#define TARGET_LINUX_SYS_epoll_wait		256
#define TARGET_LINUX_SYS_remap_file_pages	257
#define TARGET_LINUX_SYS_set_tid_address	258
#define TARGET_LINUX_SYS_timer_create	259
#define TARGET_LINUX_SYS_timer_settime	(TARGET_LINUX_SYS_timer_create+1)
#define TARGET_LINUX_SYS_timer_gettime	(TARGET_LINUX_SYS_timer_create+2)
#define TARGET_LINUX_SYS_timer_getoverrun	(TARGET_LINUX_SYS_timer_create+3)
#define TARGET_LINUX_SYS_timer_delete	(TARGET_LINUX_SYS_timer_create+4)
#define TARGET_LINUX_SYS_clock_settime	(TARGET_LINUX_SYS_timer_create+5)
#define TARGET_LINUX_SYS_clock_gettime	(TARGET_LINUX_SYS_timer_create+6)
#define TARGET_LINUX_SYS_clock_getres	(TARGET_LINUX_SYS_timer_create+7)
#define TARGET_LINUX_SYS_clock_nanosleep	(TARGET_LINUX_SYS_timer_create+8)
#define TARGET_LINUX_SYS_statfs64		268
#define TARGET_LINUX_SYS_fstatfs64		269
#define TARGET_LINUX_SYS_tgkill		270
#define TARGET_LINUX_SYS_utimes		271
#define TARGET_LINUX_SYS_fadvise64_64	272
#define TARGET_LINUX_SYS_vserver		273
