# Copyright 2010-2024 Free Software Foundation, Inc.

# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.
load_lib dwarf.exp

# This test can only be run on targets which support DWARF-2 and use gas.
require dwarf2_support

standard_testfile .S

if { [gdb_compile "${srcdir}/${subdir}/${srcfile}" "${binfile}" object {}] != "" } {
    return -1
}

clean_restart

gdb_test_no_output "maint set dwarf synchronous on"

set host_binfile [gdb_remote_download host $binfile]
gdb_test_no_output "set complaints 100"
set w1 0
set w2 0
gdb_test_multiple "file $host_binfile" "file command" {
    -re "\r\nReading symbols from \[^\r\n\]*\\.\\.\\." {
	exp_continue
    }
    -re "^\r\nDuring symbol reading: location description stack underflow" {
	set w1 1
	exp_continue
    }
    -re "^\r\nDuring symbol reading: location description stack overflow" {
	set w2 1
	exp_continue
    }
    -re -wrap "" {
	pass $gdb_test_name
    }
}

set readnow_p [readnow]

if { $readnow_p } {
    setup_kfail "gdb/26796" *-*-*
}
gdb_assert {$w1 && $w2}

gdb_test "p underflow" {Asked for position 0 of stack, stack only has 0 elements on it\.}
gdb_test "p overflow" " = 2"
