# Copyright 2012-2024 Free Software Foundation, Inc.

# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.

load_lib dwarf.exp

# This test can only be run on targets which support DWARF-2 and use gas.
require dwarf2_support

standard_testfile .S

require is_x86_64_m64_target

# We can't use prepare_for_testing here because we need to check the
# 'file' command's output.
if {[build_executable $testfile.exp $testfile $srcfile {nodebug quiet}]} {
    return -1
}

clean_restart

gdb_test_no_output "set breakpoint pending off"
gdb_test_no_output "maint set dwarf synchronous on"

set host_binfile [gdb_remote_download host $binfile]

# First test that reading symbols fails.
gdb_test "file $host_binfile" \
    {Reading symbols.*Dwarf Error: wrong version in compilation unit header \(is 153, should be 2, 3, 4 or 5\).*} \
    "file $testfile"

# We can't use proc readnow, because the PR makes it return 0.
gdb_test_multiple "maint print objfiles $host_binfile" "" {
    -re "^maint print objfiles \[^\r\n\]*\r\n$gdb_prompt $" {
	setup_kfail "gdb/26797" *-*-*
    }
    -re -wrap "" {
    }
}

# Now check that we can still break given the minimal symbol.
gdb_test "break -q main" "Breakpoint $decimal.*"
