# Copyright 2012-2024 Free Software Foundation, Inc.
#
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.
load_lib dwarf.exp

# This test can only be run on targets which support DWARF-2 and use gas.
require dwarf2_support

# Some targets have leading underscores on assembly symbols.
set additional_flags [gdb_target_symbol_prefix_flags_asm]

standard_testfile .S
if {[prepare_for_testing "failed to prepare" $testfile $srcfile \
	$additional_flags]} {
    return -1
}

# Here should be GDB-computed "Compilation directory is".
gdb_test "list gcc42" ".*"
gdb_test "info source" "\r\nCurrent source file is dw2-compdir-oldgcc42.S\r\nCompilation directory is /dir/d\r\n.*" \
	 "info source gcc42"

# Here should not be GDB-computed "Compilation directory is".
gdb_test "list gcc43" ".*"
set test "info source gcc43"
gdb_test_multiple "info source" $test {
    -re "\r\nCompilation directory is .*\r\n$gdb_prompt $" {
	fail $test
    }
    -re "\r\nCurrent source file is dw2-compdir-oldgcc43.S\r\n.*\r\n$gdb_prompt $" {
	pass $test
    }
}
