# Copyright 2012-2024 Free Software Foundation, Inc.

# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.
load_lib dwarf.exp

load_lib dwarf.exp

# This test can only be run on targets which support DWARF-2 and use gas.
require dwarf2_support

standard_testfile .c .S

set asm_file [standard_output_file $srcfile2]
Dwarf::assemble $asm_file {
    global srcdir subdir srcfile

    cu {} {
	DW_TAG_compile_unit {
	    {DW_AT_language @DW_LANG_C_plus_plus}
	    {DW_AT_name     $srcfile}
	    {DW_AT_comp_dir /tmp}
	} {
	    declare_labels myint

	    myint: DW_TAG_base_type {
		{DW_AT_byte_size 1 DW_FORM_sdata}
		{DW_AT_encoding  @DW_ATE_signed}
		{DW_AT_name      myint}
	    }

	    DW_TAG_namespace {} {
		DW_TAG_variable {
		    {DW_AT_name v}
		    {DW_AT_linkage_name _ZN12_GLOBAL__N_11vE}
		    {DW_AT_location {
			DW_OP_addr [gdb_target_symbol _ZN12_GLOBAL__N_11vE]
		    } SPECIAL_expr}
		    {DW_AT_type :$myint}
		}
	    }
	}
    }
}

if {[prepare_for_testing ${testfile}.exp ${testfile} \
	 [list $srcfile $asm_file] {nodebug}] } {
    return -1
}

gdb_test "ptype '(anonymous namespace)::v'" "type = myint"
gdb_test "p/d '(anonymous namespace)::v'" " = 1"
