# Copyright 2020-2024 Free Software Foundation, Inc.

# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.

# Check that symtab user and includes are present after symtab expansion
# triggered by an include file.

load_lib dwarf.exp

# This test can only be run on targets which support DWARF-2 and use gas.
require dwarf2_support

standard_testfile main.c .S

# Create the DWARF.
set asm_file [standard_output_file $srcfile2]
Dwarf::assemble $asm_file {
    declare_labels partial_label lines_label
    global srcdir subdir srcfile

    cu {} {
	partial_label: partial_unit {} {
	}
    }

    cu {} {
	compile_unit {
	    {language @DW_LANG_C}
	    {stmt_list ${lines_label} DW_FORM_sec_offset}
	} {
	    imported_unit {
		{import $partial_label ref_addr}
	    }
	}
    }

    lines {version 2} lines_label {
	include_dir "${srcdir}/${subdir}"
	file_name "dw2-symtab-includes.h" 1
	program {
	    DW_LNS_advance_line 1
	}
    }
}

if { [prepare_for_testing "failed to prepare" $testfile \
	  "${asm_file} ${srcfile}" {}] } {
    return -1
}

# Check that no symtabs are expanded.
set test "no symtabs expanded"
if { [readnow] } {
    unsupported $test
    return -1
}
gdb_test_no_output "maint info symtabs" $test

# Expand dw2-symtab-includes.h symtab
gdb_test "maint expand-symtab dw2-symtab-includes.h"

# Check that there are includes.
gdb_test "maint info symtabs" \
    "\r\n    \\( includes\r\n.*" \
    "check symtab includes"
