# Copyright 2010-2024 Free Software Foundation, Inc.

# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.
load_lib dwarf.exp

# This test can only be run on targets which support DWARF-2 and use gas.
require dwarf2_support

standard_testfile .S

# First try referencing DW_AT_frame_base which is not defined.
if  { [gdb_compile "${srcdir}/${subdir}/${srcfile}" "${binfile}" object {}] != "" } {
    return -1
}

clean_restart $testfile

# C language would just naively print:
# type = void (*)(void (*)(void (*)(void (*)(void (*)(...
# While modula-2 prints:
# type = POINTER TO PROCEDURE
gdb_test "set language modula-2"

# The first access (as we do not use -readnow) crashes GDB.
gdb_test "ptype v"

gdb_test "p 1" " = 1" "alive"
