# Copyright 2020-2024 Free Software Foundation, Inc.

# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.

# Test dwarf4 signatured types (DW_TAG_type_unit).

standard_testfile .cc

# This test is intended for targets which support DWARF-4.
# Since we pass an explicit -gdwarf-4 -fdebug-types-section to the compiler,
# we let that be the test of whether the target supports it.

if { [prepare_for_testing "failed to prepare" "${testfile}" \
	  $srcfile {debug c++ additional_flags=-gdwarf-4 \
			additional_flags=-fdebug-types-section}] } {
    return -1
}

if ![runto_main] {
    return -1
}

gdb_test "ptype X" "type = struct X {.*"
gdb_test "ptype Y" "type = struct Y {.*"
gdb_test "ptype Z" "type = struct Z {.*"
