# Copyright 2010-2024 Free Software Foundation, Inc.

# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.

# Test dwarf4 signatured types (DW_TAG_type_unit).

standard_testfile .cc -b.cc

include_file dw4-sig-types.h

# This test is intended for targets which support DWARF-4.
# Since we pass an explicit -gdwarf-4 -fdebug-types-section to the compiler,
# we let that be the test of whether the target supports it.

if { [prepare_for_testing "failed to prepare" "${testfile}" \
	  [list $srcfile $srcfile2] \
	  {debug c++ additional_flags=-gdwarf-4 additional_flags=-fdebug-types-section}] } {
    return -1
}

# Stress test gdb's handling of cached comp units, disable the cache.
gdb_test_no_output "maint set dwarf max-cache-age 0"

if ![runto_main] {
    return -1
}

# Bring symtab for myset into gdb.
gdb_test "p myset" ".*"

# This is enough to trigger the problem in PR 11942.
gdb_breakpoint "foo"
gdb_continue "foo"
