# Copyright 2022-2024 Free Software Foundation, Inc.

# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.

load_lib dwarf.exp

standard_testfile index.cc

set opts {}
lappend opts debug
lappend opts additional_flags=-std=c++11

if {[prepare_for_testing "failed to prepare" "${testfile}" \
	 [list ${srcfile}] $opts]} {
    return -1
}

# The bug was that gdb would crash when saving.
set output_dir [host_standard_output_file ""]
set cmd "save gdb-index"
gdb_test_multiple "$cmd $output_dir" $cmd {
    -re -wrap "Cannot use an index to create the index.*" {
	unsupported $gdb_test_name
    }
    -re "^$cmd \[^\r\n\]*\r\n$gdb_prompt $" {
	pass $gdb_test_name
    }
}
