# Copyright 2022-2024 Free Software Foundation, Inc.

# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.

standard_testfile .c

if [prepare_for_testing "failed to prepare" $testfile $srcfile \
	{debug nowarnings}] {
    return -1
}

set cmd "ptype main"

set re \
    [multi_line \
	 $cmd \
	 "type = int \\(void\\)"]

with_complaints 5 {
    gdb_test $cmd $re "$cmd without complaints"
}
