# Copyright 2012-2024 Free Software Foundation, Inc.

# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.

# A testcase to trigger the code path in bug 13961.

load_lib dwarf.exp

# This test can only be run on targets which support DWARF-2 and use gas.
require dwarf2_support

# Some targets have leading underscores on assembly symbols.
set additional_flags [gdb_target_symbol_prefix_flags_asm]

standard_testfile .S

if { [prepare_for_testing "failed to prepare" ${testfile} ${srcfile} \
	${additional_flags}] == -1 } {
    return -1
}

gdb_test "break -q main" "Breakpoint.*at.*"

# If we get this far gdb didn't crash.
pass $testfile

# Regression test for PR symtab/30739.
gdb_test_multiple "maint print objfiles $binfile" "no foo::foo" {
    -re -wrap "\r\n *qualified: *foo::foo\r\n.*" {
	fail $gdb_test_name
    }
    -re -wrap "" {
	pass $gdb_test_name
    }
}
