# Copyright 2009-2024 Free Software Foundation, Inc.

# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.
load_lib dwarf.exp

# Test DW_OP_stack_value and DW_OP_implicit_value.

# This test can only be run on targets which support DWARF-2 and use gas.
# This test can only be run on x86 targets.
require dwarf2_support is_x86_like_target

standard_testfile .S

if {[prepare_for_testing "failed to prepare" $testfile \
	 [list $srcfile] [list {additional_flags=-nostdlib}]]} {
    return -1
}

if ![runto_main] {
    return -1
}

gdb_test "break valop.c:19" "Breakpoint 2.*" "set breakpoint for valop"
gdb_continue_to_breakpoint "continue to breakpoint for valop"

gdb_test "print uses_stack_op" " = 24" "print uses_stack_op"
gdb_test "print uses_lit_op" " = 2147483648" "print uses_lit_op"
