# Copyright (C) 2023-2024 Free Software Foundation, Inc.

# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.

# This file is part of the GDB testsuite.
# It tests printing of a global stub without inferior.

require allow_cplus_tests

standard_testfile .cc
set objfile [standard_output_file ${testfile}.o]

if { [gdb_compile $srcdir/$subdir/$srcfile $objfile object \
	  {c++ debug}] != "" } {
    untested "failed to compile"
    return -1
}

clean_restart $objfile

gdb_test "print s" " = <incomplete type>"
