# Copyright 2020-2024 Free Software Foundation, Inc.
#
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.

# This file is part of the gdb testsuite.

# Test size of arrays of stubbed types (structures where the full definition
# is not immediately available).

require allow_cplus_tests

standard_testfile .cc stub-array-size2.cc

include_file stub-array-size.h

if {[prepare_for_testing "failed to prepare" $testfile "$srcfile $srcfile2" \
	{c++ debug}]} {
    return -1
}

gdb_test "print sizeof(a)/sizeof(a\[0\])" "10"
