# Copyright 2019-2024 Free Software Foundation, Inc.

# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.

# Test the use of 'set prinnt max-depth' when printing modula2 structures.

standard_testfile

if {[prepare_for_testing "failed to prepare" $testfile $srcfile {debug quiet}]} {
    return -1
}

if {![runto_main]} {
    return -1
}

gdb_breakpoint [gdb_get_line_number "Break here"]
gdb_continue_to_breakpoint "breakpoint"

gdb_test "set lang modula-2" ".*does not match.*" "switch to modula-2"

gdb_print_expr_at_depths "s3" [list "{...}" \
				    "{s2 = {...}}" \
				    "{s2 = {str = \"abcde\\\\000fghi\", s1 = {...}}}" \
				    "{s2 = {str = \"abcde\\\\000fghi\", s1 = {a = 3, b = 4}}}"]
