# Copyright 2011-2024 Free Software Foundation, Inc.
#
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.

standard_testfile
set srcmainfile ${testfile}-main.c
set objfile [standard_output_file ${testfile}.o]
set objmainfile [standard_output_file ${testfile}-main.o]
set executable ${testfile}

if { [gdb_compile ${srcdir}/${subdir}/${srcfile} ${objfile} object {debug}] != ""
     || [gdb_compile ${srcdir}/${subdir}/${srcmainfile} ${objmainfile} object {}] != ""
     || [gdb_compile_pthreads "${objfile} ${objmainfile}" ${binfile} executable {}] != ""} {
    return -1
}

clean_restart ${executable}

if ![runto_main] {
    return 0
}

# FAIL was: type = <thread local variable, no debug info>
gdb_test "whatis tls_var" {type = const char \*}

# FAIL was: $1 = 4195832
gdb_test "print tls_var" { = 0x[0-9a-f]+ "hello"}
