# This testcase is part of GDB, the GNU debugger.
#
# Copyright 2013-2024 Free Software Foundation, Inc.
#
# Contributed by Intel Corp. <markus.t.metzger@intel.com>
#
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.

require allow_btrace_tests

standard_testfile

# We expect a specific function call history.  This gets messed up with
# PIE on 32-bit.
#
# Also discard local symbols.
if [prepare_for_testing "failed to prepare" $testfile $srcfile \
	{ldflags=-Wl,-x nopie}] {
    return -1
}

if ![runto test] {
    return -1
}

# we want to see the full trace for this test
gdb_test_no_output "set record function-call-history-size 0"

# trace from one call of test to the next
gdb_test_no_output "record btrace"
gdb_continue_to_breakpoint "cont to test" ".*test.*"

# show the flat branch trace
gdb_test "record function-call-history 1" [multi_line \
  "1\ttest" \
  "2\t\\\?\\\?" \
  "3\t\\\?\\\?" \
  "4\t\\\?\\\?" \
  "5\ttest" \
  "6\tmain" \
  "7\ttest" \
  ] "flat"

# show the branch trace with calls indented
gdb_test "record function-call-history /c 1" [multi_line \
  "1\t  test" \
  "2\t    \\\?\\\?" \
  "3\t      \\\?\\\?" \
  "4\t    \\\?\\\?" \
  "5\t  test" \
  "6\tmain" \
  "7\t  test" \
  ] "indented"
