#!/bin/bash

qemu_args=()
while [[ "$1" != "" ]]
do
    case "$1" in
    -Wq,*)
        qemu_args+=("$(echo "$1" | cut -d, -f2-)")
        shift
        ;;
    *=*)
        qemu_args+=("-E")
        qemu_args+=("\"$1\"")
        shift
        ;;
    env)
        shift
        ;;
    *)
        break
        ;;
    esac
done

timeout 10m qemu-riscv32 -L "${RISC_V_SYSROOT}" ${qemu_args[@]} "$@"
out="$?"
if [[ "$out" == "124" ]]
then
  exit 0
fi
exit "$out"
