#!/bin/bash

qemu_args=()
while [[ "$1" != "" ]]
do
    case "$1" in
    -Wq,*) qemu_args+=("$(echo "$1" | cut -d, -f2-)");;
    *) break;;
    esac
    shift
done

xlen="$(readelf -h $1 | grep 'Class' | cut -d: -f 2 | xargs echo | sed 's/^ELF//')"
qemu_args+=(-cpu rv$xlen,x-k=true);

qemu-riscv$xlen "${qemu_args[@]}" -L ${RISC_V_SYSROOT} "$@"
