.*: Assembler messages:
.*: Error: instruction cv.addn requires absolute expression
.*: Error: instruction cv.addun requires absolute expression
.*: Error: instruction cv.addrn requires absolute expression
.*: Error: instruction cv.addurn requires absolute expression
.*: Error: instruction cv.subn requires absolute expression
.*: Error: instruction cv.subun requires absolute expression
.*: Error: instruction cv.subrn requires absolute expression
.*: Error: instruction cv.suburn requires absolute expression
