# Copyright (C) 2013-2024 Free Software Foundation, Inc.

# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.

# This test case is to test the performance of GDB doing stack
# backtrace.
# There is one parameter in this test:
#  - BACKTRACE_DEPTH is the number of innermost frames that command
#    'bt' prints.

load_lib perftest.exp

require allow_perf_tests

standard_testfile .c
set executable $testfile
set expfile $testfile.exp

# make check-perf RUNTESTFLAGS='backtrace.exp BACKTRACE_DEPTH=1024'
if ![info exists BACKTRACE_DEPTH] {
    set BACKTRACE_DEPTH 64
}

PerfTest::assemble {
    global BACKTRACE_DEPTH
    global srcdir subdir srcfile

    set compile_flags {debug}
    lappend compile_flags "additional_flags=-DBACKTRACE_DEPTH=${BACKTRACE_DEPTH}"

    if { [gdb_compile "$srcdir/$subdir/$srcfile" ${binfile} executable $compile_flags] != ""} {
	return -1
    }

    return 0
} {
    global binfile

    clean_restart $binfile

    if ![runto_main] {
	return -1
    }

    gdb_breakpoint "fun2"
    gdb_continue_to_breakpoint "fun2"

    return 0
} {
    global BACKTRACE_DEPTH

    gdb_test_python_run "BackTrace\($BACKTRACE_DEPTH\)"

    return 0
}
