#!/bin/bash
# This script emulates the cp -s command, which Mac OS doesn't support.

set -e

pushd $1 > /dev/null
SRCDIR=`pwd`
DIRS=`find . -type d`
FILES=`find . -type f`
popd > /dev/null

pushd $2 > /dev/null
for i in $DIRS; do
  mkdir -p $i
done
for i in $FILES; do
  ln -f -s $SRCDIR/$i $i
done
popd > /dev/null
