#!/usr/bin/env python3
import sys

# cf. <https://docs.python.org/3/library/venv.html#how-venvs-work>
# cf. <https://peps.python.org/pep-0405/#specification>
is_venv = (sys.prefix != getattr(sys, "base_prefix", sys.prefix))

print('Python is {}running under a virtual environment.'.format(
    '' if is_venv else 'not '), file=sys.stderr)
sys.exit(0 if is_venv else 1)
