# Copyright 2014-2024 Free Software Foundation, Inc.

# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.  */

require supports_reverse supports_process_record

standard_testfile

if {[prepare_for_testing "failed to prepare" $testfile [list $srcfile]]} {
    return -1
}

# The bug is a regression in the sequence "run; record; run".
runto_main
gdb_test_no_output "record" "turn on process record"

gdb_run_cmd
gdb_test_multiple "" "restarting inferior" {
    -re "Breakpoint .*${gdb_prompt} " {
	pass "restarting inferior"
    }
}
