name: "Download Comparison Artifacts"
description: "Downloads artifacts needed for run comparison"
inputs:
  report-artifact-name:
    required: true
  binary-artifact-name:
    required: true
  github-token:
    required: true

runs:
  using: "composite"
  steps:
    - name: Download report from this workflow
      if: '!cancelled()'
      uses: actions/download-artifact@v3
      with:
        name: ${{ inputs.report-artifact-name }}
        path: "./logs"
      continue-on-error: true

    - name: Download report from another workflow
      if: ${{ !cancelled() && hashFiles(format('./logs/{0}', inputs.report-artifact-name)) == '' }}
      shell: bash
      run: |
        pip install pygithub requests
        python ./scripts/download_single_artifact.py -name ${{ inputs.report-artifact-name }} -token ${{ inputs.github-token }} -outdir logs
      continue-on-error: true

    - name: Download rv32 non-multilib binary
      if: ${{ !cancelled() && hashFiles(format('./logs/{0}', inputs.report-artifact-name)) == '' }}
      uses: actions/download-artifact@v3
      with:
        name: ${{ inputs.binary-artifact-name }}
        path: "./temp"
      continue-on-error: true

    - name: Download rv32 non-multilib binary from another workflow
      if: ${{ !cancelled() && hashFiles(format('./logs/{0}', inputs.report-artifact-name)) == '' }} && hashFiles(format('./temp/{0}', inputs.binary-artifact-name))
      shell: bash
      run: |
        pip install pygithub requests
        python ./scripts/download_single_artifact.py -name ${{ inputs.binary-artifact-name }} -token ${{ inputs.github-token }} -outdir temp
      continue-on-error: true
