# Copyright 2023-2024 Free Software Foundation, Inc.

# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.

require allow_fortran_tests

load_lib fortran.exp

standard_testfile .f90

if {[prepare_for_testing ${testfile}.exp ${testfile} ${srcfile} {debug f90}]} {
    return -1
}

if {![fortran_runto_main]} {
    perror "Could not run to main."
    return
}

gdb_breakpoint [gdb_get_line_number "Break here"]
gdb_continue_to_breakpoint "continue to bar"

gdb_test "bt" \
    [multi_line \
	 "#0\[ \t\]*bar \\(\\) at \[^\r\n\]+" \
	 "#1\[ \t\]*$hex in foo \\(\\) at \[^\r\n\]+" \
	 "#2\[ \t\]*$hex in \(?:MAIN__\|main\) \\(\\) at \[^\r\n\]+" ]
