# Copyright (C) 2010-2024 Free Software Foundation, Inc.

# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.

# Test error while loading *-gdb.py.  IBM1047 is chosen as possibly supported
# by glibc but unsupported by Python

set testfile "py-error"

load_lib gdb-python.exp

require allow_python_tests

# Start with a fresh gdb.
gdb_exit
gdb_start

set charset "IBM1047"

set test2 "main reached"

set test "set host-charset $charset"
set test_regex [string_to_regexp $test]
gdb_test_multiple $test $test {
    -re "^$test_regex\r\n$gdb_prompt $" {
	pass $test
    }
    -re "^$test_regex\r\nUndefined item: \"$charset\"\\.\r\n$gdb_prompt $" {
	xfail $test
	untested $test2
	set test2 ""
    }
}

if {$test2 == ""} {
    return 0
}

set remote_python_file [gdb_remote_download host \
			    ${srcdir}/${subdir}/${testfile}.py]

# argc=LookupError: unknown encoding: IBM1047
gdb_test "source $remote_python_file" "Traceback.*ClassName.*\r\nLookupError: unknown encoding: $charset" $test2

gdb_test "p 1" " = 1" "no delayed error"
