# Copyright (C) 2013-2024 Free Software Foundation, Inc.

# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.

# This file is part of the GDB testsuite.

# This test case is copied from PR12929.
# http://sourceware.org/bugzilla/show_bug.cgi?id=12929

standard_testfile

require can_spawn_for_attach allow_python_tests

load_lib gdb-python.exp

if { [prepare_for_testing "failed to prepare" ${testfile} ${srcfile}] } {
    return -1
}

set test_spawn_id [spawn_wait_for_attach $binfile]
set testpid [spawn_id_get_pid $test_spawn_id]

# Test command 'where' is executed when command 'attach' is done, otherwise
# function 'sleep' may not show up in backtrace.

gdb_test "python gdb.execute(\"attach $testpid\"); gdb.execute(\"where\")" \
    "in .*sleep \\(.*\\) .* in foo1 \\(\\) at .* in foo2 \\(\\) at .*" \
    "attach and where"

kill_wait_spawned_process $test_spawn_id
