# Miscellaneous FRV simulator testcases.

sim_init

# all machines
set all_machs "frv fr500 fr550 fr400 fr405 fr450"
set cpu_option -mcpu

# The .ms suffix is for "miscellaneous .s".
foreach src [lsort [glob -nocomplain $srcdir/$subdir/*.ms]] {
    # If we're only testing specific files and this isn't one of them, skip it.
    if ![runtest_file_p $runtests $src] {
	continue
    }
    run_sim_test $src $all_machs
}
