.* Assembler messages:
.*:5: Error: operand type mismatch for `urdmsr'
.*:6: Error: operand type mismatch for `urdmsr'
.*:7: Error: operand type mismatch for `urdmsr'
.*:8: Error: operand type mismatch for `urdmsr'
.*:9: Error: operand type mismatch for `uwrmsr'
.*:10: Error: operand type mismatch for `uwrmsr'
.*:11: Error: operand type mismatch for `uwrmsr'
.*:12: Error: operand type mismatch for `uwrmsr'
